### ISSUE TITLE
[Windows] `--local-executor 0` must be default as local execution fails out-of-box

### ISSUE THREAD

**Issue by sowmya-jaxl** [abhinavsingh/proxy.py#1001]
See https://github.com/abhinavsingh/proxy.py/issues/1000 for background.

IMHO, `--local-executor 0` must be made default for Windows operating system.

**Comment by abhinavsingh** [comment]
Closing this, as it turned out problem was with `--local-executor` flag logic and not the default value.  See https://github.com/abhinavsingh/proxy.py/pull/1008
