### ISSUE TITLE
[Devtools] Build broken due to structural changes in `chrome-devtools` npm package

### ISSUE THREAD

**Issue by yswtrue** [abhinavsingh/proxy.py#1012]
I clone latest code from git.
and make devtools get errors.

**To Reproduce**
1. clone from git
2. cd dashboard
3. npm install
4. run `make dashboard`
5. run `make devtools `

**Version information**
 - OS: manjaro 
 - Node: v17.3.0
 - npm: 6.14.6

**Additional context**
```
➜  proxy.py git:(177689c) ✗ make devtools 
pushd dashboard && npm run devtools && popd
~/Code/proxy.py/dashboard ~/Code/proxy.py

> proxy.py@1.0.0 devtools /home/yswtrue/Code/proxy.py/dashboard
> npm run build-devtools && node tsbuild/devtools.js


> proxy.py@1.0.0 build-devtools /home/yswtrue/Code/proxy.py/dashboard
> tsc --target es5 --outDir tsbuild src/core/devtools.ts

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'chrome-devtools-frontend/front_end/inspector.json'
Require stack:
- /home/yswtrue/Code/proxy.py/dashboard/tsbuild/devtools.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at setUpDevTools (/home/yswtrue/Code/proxy.py/dashboard/tsbuild/devtools.js:24:47)
    at Object.<anonymous> (/home/yswtrue/Code/proxy.py/dashboard/tsbuild/devtools.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/yswtrue/Code/proxy.py/dashboard/tsbuild/devtools.js' ]
}

Node.js v17.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proxy.py@1.0.0 devtools: `npm run build-devtools && node tsbuild/devtools.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the proxy.py@1.0.0 devtools script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yswtrue/.npm/_logs/2022-01-19T20_03_49_875Z-debug.log
make: *** [Makefile:173：devtools] 错误 1
```

**Screenshots**

**Comment by abhinavsingh** [comment]
Devtools might be broken as there are no integration tests.  Neither do I use it on a day to day basis.

I request you to kindly checkout older versions of Devtools, which should be working fine.

Most of these breakages happen due to dependabot automatic dependency updates.  Probably we must disable updates for dashboard.

Also, in future, dashboard will be deprecated.  As maintaining it is a PITA.

Let me know if 2.3.x doesn't work as expected for you.

**Comment by abhinavsingh** [comment]
I took a deep look (sorry just woke up back then).  I think you might be missing `npm install`.

I double checked, `make dashboard` doesn't do `npm install` by default.

Let me know, if it works, we must update read me instructions documented [here](https://github.com/abhinavsingh/proxy.py#run-dashboard) 

Thank you

**Comment by abhinavsingh** [comment]
@yswtrue Further, looks like build is still broken due to changes in `chrome-devtools` NPM package.

I'll send out a fix and also add an integration test for `devtools`.  We have integration for dashboard builds but not devtools yet.

**Comment by abhinavsingh** [comment]
jFYI https://github.com/abhinavsingh/proxy.py/pull/1015 fixes the build issue and also adds `devtools` as part of GHA workflows.   At-least we can guarantee that `devtools` build will not go broken again (silently) :D

**Comment by yswtrue** [comment]
I have run `npm install`, I will try it later. Thanks.

> jFYI #1015 fixes the build issue and also adds `devtools` as part of GHA workflows. At-least we can guarantee that `devtools` build will not go broken again (silently) :D

**Comment by yswtrue** [comment]
I pull the latest code, and it works now.

**Comment by abhinavsingh** [comment]
> I pull the latest code, and it works now.

Awesome, thanks for reporting it.

**Comment by yswtrue** [comment]
But I still can't display traffic inspect

![image](https://user-images.githubusercontent.com/1270490/150335618-018480ae-ac66-4949-976b-ef112965ded0.png)

**Comment by abhinavsingh** [comment]
Yes that can very well happen.  `chrome-devtools` keep changing their internal architecture.  Either we must pin `chrome-devtools` dependency (which we haven't) or someone needs to keep it up-to date.  As I mentioned earlier, there are no integration test for devtool working via dashboard.  Hence it's easy for us to miss such breaking upgrades to `chrome-devtools`.

Irrespective of the UI not loading, you should be able to see `proxy.py` instance sending realtime updates about connections as they happen.  You can use `proxy.py` devtools websocket point instead and integrate directly with your instance of devtools (e.g. one that comes with chrome).  It should work out of box.  devtools app that we have built (part of the repo), keeps going out of sync, giving a broken dashboard inspect traffic experience.

<img width="1668" alt="Screen Shot 2022-01-20 at 5 58 12 PM" src="https://user-images.githubusercontent.com/126065/150339380-b5a0d169-7e7b-413c-b9e3-777360075322.png">

**Comment by yswtrue** [comment]
ok, I will try it.

**Comment by abhinavsingh** [comment]
Hint: Search for "using custom CRDT websocket endpoint with devtools".

As far as I know, devtools support this out of box, so you should achieve success.

Do share your findings with us.  Thank you.
