### ISSUE TITLE
Proxy.py v1.0.0 fails on Python 2.7

### ISSUE THREAD

**Issue by dagwieers** [abhinavsingh/proxy.py#104]
We are using Proxy.py in performing integration testing in Travis.

Since Proxy.py hit pypi our integration tests fail like this on Python v2.7
```
Collecting proxy.py (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a5/b0/830dd2ff2589bb44202ab57c4e4b48b082928cc24568e9e7774a4a858fb1/proxy.py-1.0.0.tar.gz (97kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LPYus2/proxy.py/setup.py", line 12, in <module>
        import proxy
      File "proxy.py", line 57
        DEFAULT_DISABLE_HEADERS: List[bytes] = []
                               ^
    SyntaxError: invalid syntax
```

https://travis-ci.org/emilsvennesson/script.module.inputstreamhelper/jobs/590604886

**Comment by abhinavsingh** [comment]
Oops!!! I was delayed the release for months because of similar expected issues.  Unfortunately `proxy.py==1.0.0` doesn't support `Python 2.7`.  If you cannot upgrade to `Python 3+`, please fallback to `proxy.py==0.3`

**Comment by dagwieers** [comment]
No problem, that is what I did. I now noticed that on Pypi support for v2.7 was not even mentioned, so I guess this was to be expected :-) We still have to support Python 2.7 because Kodi add-ons currently still only support Python v2.7 (the upcoming release will be Python 3, however older Kodi releases will still be around for quite some time...)

**Comment by dagwieers** [comment]
BTW We do get a 'Bad statusline' exception on Python v2.7 from time to time, not sure if you are aware of this, and whether you know how to work around this (apart from retrying in the client).

**Comment by abhinavsingh** [comment]
Great, agreed its a painful migration for larger projects, though soon official Python 2.7 support will also end _(January next year)_.

> BTW We do get a 'Bad statusline' exception on Python v2.7 from time to time, not sure if you are aware of this, and whether you know how to work around this (apart from retrying in the client).

I haven't seen one yet, bad statusline sounds looks like a bad request to me.  Are you getting this from proxy.py, Can you help with exception stack trace or raw http packet that were sent to proxy?

**Comment by dagwieers** [comment]
A retry of the exact same request fixes it. We never saw this on Python 3, that is why I never reported it. I guess with v1.0.0 out this is no longer a concern ;-)
