### ISSUE TITLE
No module named 'typing_extensions'

### ISSUE THREAD

**Issue by mbatrawi** [abhinavsingh/proxy.py#108]
python3.6 proxy.py

```Traceback (most recent call last):
  File "proxy.py", line 37, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

for develop  and app branch

**Comment by abhinavsingh** [comment]
pip install typing_extensions.

I realized that depending upon OS/Python version, "Protocol" class might be
within "typing" module or in "typing_extensions".

Might need to add a requirements file for this dependency.

**Comment by abhinavsingh** [comment]
v1.1.0 explicitly adds `typing_extensions` as a requirement now.
