### ISSUE TITLE
Loading custom plugins

### ISSUE THREAD

**Issue by NikolayPogoreliy** [abhinavsingh/proxy.py#110]
Hello.
I've use `proxy.py` with `venv`. I've wrote my own plugin, placed in `my_proxy.MyCustomPlugin`. But when I try to connect it, I've receive an error:

`ModuleNotFoundError: No module named 'my_proxy'`

**Comment by abhinavsingh** [comment]
Make sure `my_proxy` module is listed among `PYTHONPATH`.  Your plugin module must be discoverable for it to load.

**Comment by drzraf** [comment]
Yes you're right. I got it working. For those unfamiliar with python import syntax, you want to document that it should looks like `<file>.<ClassName>`.
