### ISSUE TITLE
Can't open the dashboard

### ISSUE THREAD

**Issue by Thoufak** [abhinavsingh/proxy.py#1130]
**To reproduce**
1. Run `proxy.py` as `proxy --enable-dashboard --log-level d`
2. Go to http://localhost:8899/dashboard
3. Get 404.

**Expected behavior**
The dashboard opens.

**Version information**
 - OS: macOS
 - Browser: Yandex browser/Chrome
 - Device: MacBook Air
 - proxy.py Version: 2.4.1

**Logs**
[Proxy py logs.txt](https://github.com/abhinavsingh/proxy.py/files/8531298/Proxy.py.logs.txt)

**Comment by Thoufak** [comment]
Found the solution [here](https://proxypy.readthedocs.io/en/latest/#run-dashboard).

**Comment by Yusufkulcu** [comment]
> Found the solution [here](https://proxypy.readthedocs.io/en/latest/#run-dashboard).

I can't run the make command on my Windows Device, how can I solve it, can you help
