### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by limbo127** [abhinavsingh/proxy.py#114]
We are using proxy with a lot of  connect method 

```
2019-10-07 10:45:42,871 - ERROR - pid:30929 - run:1588 - Exception while handling connection <socket.socket fd=19, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('fd00:6::8e2:97ff:fe2e:f1ea', 8081, 0, 0), raddr=('fd00:6:df94:0:f64d:30ff:fe65:ca85', 45096, 0, 0)> with reason ValueError('filedescriptor out of range in select()')
Traceback (most recent call last):
  File "/usr/local/bin/proxy.py", line 1580, in run
    teardown = self.run_once()
  File "/usr/local/bin/proxy.py", line 1542, in run_once
    read_desc, write_desc, err_desc, 1)
ValueError: filedescriptor out of range in select()
```

**Comment by abhinavsingh** [comment]
We'll need more info to dig deeper:

1. What's your current `ulimit -n` setting
2. Have you already tried bumping it up?
3. How many requests per sec are you sending to proxy.

Thank you

**Comment by limbo127** [comment]
ulimit -n => 500000
I do not test the open file option, i 'm trying now. 
thanks

**Comment by abhinavsingh** [comment]
Thats some insane number, are you sure your system supports this value.

Also, it will be helpful for us to check how files `proxy.py` and its worker processes have opened.  Run this command:

```
PROXY_PY_PID=4387;
lsof -p $PROXY_PY_PID | wc -l;
pgrep -P $PROXY_PY_PID | while read pid; do lsof -p $pid | wc -l; done;
```

NOTE:
1. Tested only on Mac
2. Expects `pgrep` command, most likely on your system already

**Comment by limbo127** [comment]
Ok, i'm restarting proxy as : 
proxy.py --port 8081 --hostname fd00:6::8e2:97ff:fe2e:f1ea --open-file-limit 50000  --num-workers 16
i give you more info about lsof

**Comment by abhinavsingh** [comment]
I'll recommend you to also manually run:
`ulimit -n 50000`

You may have to `sudo su`.

**Comment by abhinavsingh** [comment]
> I'll recommend you to also manually run:
> `ulimit -n 50000`
> 
> You may have to `sudo su`.

If you are not getting an exception while starting `proxy.py`, then most likely your user account is already setup.  Example, for me on my Mac, giving a random high value results in exception:

```
$ ./proxy.py --log-level d --open-file-limit 30000
Traceback (most recent call last):
  File "./proxy.py", line 2077, in <module>
    main(sys.argv[1:])  # pragma: no cover
  File "./proxy.py", line 2011, in main
    set_open_file_limit(args.open_file_limit)
  File "./proxy.py", line 1778, in set_open_file_limit
    resource.RLIMIT_NOFILE, (soft_limit, curr_hard_limit))
ValueError: current limit exceeds maximum limit
```

Let's get `lsof` info for more insights.  Also let me know how many concurrent requests are you trying for :)  Thank you.

**Comment by abhinavsingh** [comment]
@limbo127 Looks like `--open-file-limit` flag worked out for you.  But I am still curious how far were you able to stress test `proxy.py`.  Will be great if you can share some details.  Thank you.
