### ISSUE TITLE
TLS Interception - "FIleNotFoundError" when wrapping client for upstream

### ISSUE THREAD

**Issue by KeanuNys** [abhinavsingh/proxy.py#1146]
**Check FAQs**
The FAQ describes a similar issue, but I'm not sure that it is the same issue that I have as the error is a bit different ( https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception ) 

**Describe the bug**
I've been running into a lot of issues when trying to set up an HTTPS proxy with TLS interception. I want it to run from a python script and am therefore following some simple examples I found in other posts regarding this topic, but none seem to cover the issue I run into.

[The documentation](https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception) goes over some known issues with message "OSError when wrapping client" and one of the following SSL error messages: "TLSV1_ALERT_UNKNOWN_CA", "CERTIFICATE_VERIFY_FAILED" or "SSLEOFError".
However, in my case, none of these errors is shown. Instead, a FIleNotFoundError is returned without referring to which file wasn't found, making it a bit hard to troubleshoot without previous knowledge of the tool.

I have tried placing all the `.pem` files in:
*  The same directory as the python script
* The `~\.proxy\certificates` directory
* Tried referring to them with absolute paths
* Tried referring to them with absolute paths using double backslashes `\\`
* Tried setting the `ca_cert_dir` to the directory the `.pem` files are stored in
But nothing seems to resolve the issue.

**To Reproduce**

I created the following small test script to attempt to intercept some connections to an HTTPS site:
```python
import ipaddress
import proxy

if __name__ == '__main__':
  proxy.main(
    hostname=ipaddress.ip_address('127.0.0.1'),
    port=8080,
    ca_key_file="ca-key.pem",
    ca_cert_file="ca-cert.pem",
    ca_signing_key_file="ca-signing-key.pem"
  )
```

On my Windows machine, I run this script with the command `python.exe testServer.py` and then I open firefox and configure the proxy server to 127.0.0.1:8080.

After doing this, the following output is returned in the console where the 

```
D:\Documents\xxx\Server>python.exe testServer.py
2022-05-10 21:52:36,038 - pid:13196 [I] plugins.load:85 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2022-05-10 21:52:36,040 - pid:13196 [I] tcp.listen:80 - Listening on 127.0.0.1:8080
2022-05-10 21:52:36,084 - pid:13196 [I] pool.setup:105 - Started 8 acceptors in threaded mode
2022-05-10 21:52:42,713 - pid:14904 [E] server.wrap_client:847 - OSError when wrapping client for upstream: www.example.com
Traceback (most recent call last):
File "D:\Python39\lib\site-packages\proxy\http\proxy\server.py", line 797, in wrap_client
generated_cert = self.generate_upstream_certificate(
File "D:\Python39\lib\site-packages\proxy\http\proxy\server.py", line 731, in generate_upstream_certificate
self.gen_ca_signed_certificate(cert_file_path, certificate)
File "D:\Python39\lib\site-packages\proxy\http\proxy\server.py", line 672, in gen_ca_signed_certificate
resp = gen_public_key(
File "D:\Python39\lib\site-packages\proxy\common\pki.py", line 114, in gen_public_key
return run_openssl_command(command, timeout)
File "D:\Python39\lib\site-packages\proxy\common\pki.py", line 225, in run_openssl_command
cmd = subprocess.Popen(
File "D:\Python39\lib\subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "D:\Python39\lib\subprocess.py", line 1420, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-05-10 21:52:42,716 - pid:14904 [I] server.access_log:384 - 127.0.0.1:2304 - CONNECT www.example.com:443 - 0 bytes - 343.70ms
```

**Expected behavior**
The expected goal that I want to achieve is to intercept HTTPS traffic and be able to modify the requests coming from the client inline before being forwarded to the server. (As well as some logging of the responses of the server).

**Version information**
 - OS: Windows 10
 - Browser: Firefox, Chrome, IE (Tried all of them)
 - Device: Laptop
 - proxy.py Version: Latest, installed today (2.4.1?)

*If it ends up being the same issue as described [here](https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception), which client/browser should I use that will not throw certificate issues when trying to proxy traffic through proxy.py?*

**Comment by abhinavsingh** [comment]
> If it ends up being the same issue as described [here](https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception), which client/browser should I use that will not throw certificate issues when trying to proxy traffic through proxy.py?

IMHO cases listed here https://github.com/abhinavsingh/proxy.py#oserror-when-wrapping-client-for-tls-interception are different from what you are seeing.  Looks like `proxy.py` is unable to find a file it is looking for.  I suspect it's openssl based upon the stacktrace.

**Comment by KeanuNys** [comment]
I might have a clue what file it can't find after further looking into this.


Looking at the code at the location of the following error: `File "D:\Python39\lib\site-packages\proxy\common\pki.py", line 114, in gen_public_key`
->
```python
def gen_public_key(
        public_key_path: str,
        private_key_path: str,
        private_key_password: str,
        subject: str,
        alt_subj_names: Optional[List[str]] = None,
        extended_key_usage: Optional[str] = None,
        validity_in_days: int = 365,
        timeout: int = 10,
) -> bool:
    """For a given private key, generates a corresponding public key."""
    with ssl_config(alt_subj_names, extended_key_usage) as (config_path, has_extension):
        command = [
            'openssl', 'req', '-new', '-x509', '-sha256',
            '-days', str(validity_in_days), '-subj', subject,
            '-passin', 'pass:%s' % private_key_password,
            '-config', config_path,
            '-key', private_key_path, '-out', public_key_path,
        ]
        if has_extension:
            command.extend([
                '-extensions', 'PROXY',
            ])
        return run_openssl_command(command, timeout)
```
We can see that it gives the "openssl" command and its parameters to the run_openssl_command() function. This function creates a subprocess for the command that was provided, as we can see in the following code.

```
def run_openssl_command(command: List[str], timeout: int) -> bool:
    cmd = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
```

However, my Windows host will not be able to start a process for the `openssl` command as that isn't a filepath to an executable that it expects.
`(This is just my guess, not sure whether I am right or whether there is some other issue). Also not sure how to fix it`

**Comment by abhinavsingh** [comment]
Correct.  If you hardcode path to your `openssl` binary, does it work fine then?  If we, we can add a flag for path to openssl in next push.

**Comment by KeanuNys** [comment]
I'll try it out with the full path in the python script calling openssl. So far it doesn't seem to directly work. I'll play around with it a bit and see if I can get it to work.

Will keep you posted.

________________________________

**Comment by KeanuNys** [comment]
Got it to work by replacing `'openssl'` by `'D:\\Program Files\\OpenSSL-Win64\\bin\\openssl.exe'`. After doing this in the pki.py file, the script runs fine :) 

The interception works, and the responses are cached correctly using the CacheResponsesPlugin. However, I did notice that some different errors are still created from time to time, but that doesn't seem to impact the websites that I am proxying that badly on first sight. `[WinError 10053] An established connection was aborted by the software in your host machine`

It says it aborted the connection, but after that it still seems to load the website eitherway and caches the response 

```
2022-05-11 08:13:42,101 - pid:4252 [I] server.access_log:384 - 127.0.0.1:3909 - CONNECT www.example.com:443 - 0 bytes - 237.09ms 
2022-05-11 08:13:42,222 - pid:25156 [E] server.wrap_client:847 - OSError when wrapping client for upstream: www.example.com
Traceback (most recent call last):
File "D:\Python39\lib\site-packages\proxy\http\proxy\server.py", line 800, in wrap_client
self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
File "D:\Python39\lib\site-packages\proxy\core\connection\client.py", line 45, in wrap
self._conn = ssl.wrap_socket(
File "D:\Python39\lib\ssl.py", line 1405, in wrap_socket
return context.wrap_socket(
File "D:\Python39\lib\ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "D:\Python39\lib\ssl.py", line 1040, in _create
self.do_handshake()
File "D:\Python39\lib\ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2022-05-11 08:13:42,224 - pid:25156 [I] server.access_log:384 - 127.0.0.1:3908 - CONNECT www.example.com:443 - 0 bytes - 357.61ms

...

2022-05-11 08:13:48,863 - pid:17268 [I] cache_responses.write_content_type:128 - Cached content file at C:\Users\xxx\.proxy\cache\content\www.example.com-e46611dab202487aa1b9cb257757d0d4.javascript
2022-05-11 08:13:48,884 - pid:10028 [I] server.access_log:384 - 127.0.0.1:3896 - CONNECT www.example.com:443 - 469 bytes - 7838.14ms
2022-05-11 08:13:48,929 - pid:10028 [I] cache_responses.write_content_type:128 - Cached content file at C:\Users\xxx\.proxy\cache\content\www.example.com-9d31702cdd7b4f12a3f2eae9ee306b97.html
```

**Comment by abhinavsingh** [comment]
Excellent news.  So we must allow users to override `openssl` path.  I have created a ticket for it.  If you want to take a stab at it and send a PR, let me know, I can guide you through.

About the error you are seeing, looks like they are harmless.  Ref https://stackoverflow.com/questions/51562067/connectionabortederror-winerror-10053-an-established-connection-was-aborted-b

<img width="764" alt="Screen Shot 2022-05-11 at 4 26 58 PM" src="https://user-images.githubusercontent.com/126065/167833833-1122db1c-9213-4e4d-bb56-882e4aeef412.png">

**Comment by abhinavsingh** [comment]
Closing this.  Issue related to `openssl` binary path override will be used to track this feature progress.  Thanks for bringing this to our highlight and all the debugging.  Best
