### ISSUE TITLE
How to modify request before send to host

### ISSUE THREAD

**Issue by knucker** [abhinavsingh/proxy.py#115]
Hi @abhinavsingh,
I'm trying to make a little modification at request body content right before it to be send to host. Is that possible by some Plugin? Or I need to overwrite the TcpConnection.send? #

**Comment by abhinavsingh** [comment]
Have you checked README.md and examples in plugin_examples.py?

**Comment by knucker** [comment]
Yes. But I din't find the object to modify.
For example I have the request:
```
POST /json.json HTTP/1.1
content-type: application/json
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.1.1; Google Build/NMF26Q)
Host: myhost.com
Connection: close
Accept-Encoding: gzip, deflate
Content-Length: 76

{"date":"2019/08/12", "payload": "c0ed2ab2961f83e06ffb857164297d8bd45709f5"}
```
and before to send to destination I want to change, for example, the date.

I tried to change the self.request in before_upstream_connection and on_upstream_connection using HttpProxyBasePlugin, but couldn't find the object to change.

**Comment by abhinavsingh** [comment]
Ideally both `before_upstream_connection` and `on_upstream_connection` will work since request haven't been sent to the server yet, hence giving a chance to modify request data.  Below is a working example _(will add this to plugin_examples.py)_.  Use following steps to verify it works:

1. Make a POST request to `httpbin.org` and ensure it returns same parameters that we passed via command line:

```
$ curl -X POST -H "Content-Type: application/json" http://httpbin.org/post -d '{"key":"value"}'
{
  "args": {}, 
  "data": "{\"key\":\"value\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "15", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.54.0"
  }, 
  "json": {
    "key": "value"
  }, 
  "origin": "1.2.3.4, 5.6.7.8", 
  "url": "https://httpbin.org/post"
}
```

2. Now lets modify outgoing request body to the server using a plugin:

```
class ModifyPostDataPlugin(proxy.HttpProxyBasePlugin):

    def before_upstream_connection(self) -> bool:
        self.request.body = b'{"key": "modified"}'
        self.request.add_header(b'content-length', proxy.bytes_(len(self.request.body)))
        return False

    def on_upstream_connection(self) -> None:
        pass

    def handle_upstream_response(self, raw: bytes) -> bytes:
        return raw

    def on_upstream_connection_close(self) -> None:
        pass
```

Start as `proxy.py --plugins plugin_examples.ModifyPostDataPlugin`

Verify via curl again, this time `httpbin.org` must return modified request that our plugin sent:

```
$ curl -x localhost:8899 -X POST -H "Content-Type: application/json" http://httpbin.org/post -d '{"key":"value"}'
{
  "args": {}, 
  "data": "{\"key\": \"modified\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "19", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.54.0"
  }, 
  "json": {
    "key": "modified"
  }, 
  "origin": "1.2.3.4, 5.6.7.8", 
  "url": "https://httpbin.org/post"
}
```

**Comment by abhinavsingh** [comment]
While this works for your use case, it will fail for large payload use cases.  Example, if client is sending data in chunks _(chunked encoding)_, `on_client_data` callback will then need to assemble the chunks before fruitfully modifying it.

It's ok if you want to modify `proxy.py` as above for your use case, but this ain't a candidate for inclusion in the core.  As recommended, better to just fallback to `before_upstream_connection` where you have access to entire client `self.request.body`.  One way to looks at it will be, your objective is to modify outgoing `POST` body not incoming chunks, let core assemble it for you.  There are also cases where you will have to `deflate` / `inflate` the body unnecessarily if client starts to send encoded data.

**Comment by knucker** [comment]
Hmm, makes sense.
I will try to use the `before_upstream_connection`.
Thank you, for the feedback!

**Comment by abhinavsingh** [comment]
@knucker jFYI, https://github.com/abhinavsingh/proxy.py/issues/126 came around and looks like adding a `handle_client_request` callback seems best approach.  I'll /cc you on the PR https://github.com/abhinavsingh/proxy.py/pull/128 which starts to add this handler.
