### ISSUE TITLE
[Reverse Proxy] Modify reverse proxy request

### ISSUE THREAD

**Issue by nettnikl** [abhinavsingh/proxy.py#1155]
**Is your feature request related to a problem? Please describe.**
I am implementing a reverse proxy which does some stuff to the requests before forwarding. I've tried flask, but i need a solution able to handle big files, so i came here. My project needs to be implemented in python for unrelated reasons.

Currently for debugging purposes i'm modifying `proxy/http/server/reverse.py:89` ff, uncommenting the "Update Host header" change, and this is fine-ish for development.
But i'm planning to use this in production, and adding more functionality there, so i'd need a way to modify requests going upstream.

**Describe the solution you'd like**
Some method to overwrite in the reverse proxy base plugin where i can modify the requests - while still being able to directly stream big upstream content (think of a TB here).

**Describe alternatives you've considered**
- implementing parts of the solution in python, and the actual handling of proxied content in nginx or similar
- forking this code and adding it directly, which makes it hard to update and maintain
- different reverse proxy projects in python (are there even any production ready ones actually?)

**Additional context**
This possibility was already suggested to be possible in https://github.com/abhinavsingh/proxy.py/issues/1045
> In-fact, we can provide a ReverseProxyBasePlugin hook which allows developers to modify the request before dispatching to upstream server.

**Comment by abhinavsingh** [comment]
IIUC correctly, we are talking about following feature

- https://github.com/abhinavsingh/proxy.py/issues/1132

We'll likely address it in upcoming release, include support for self-signed certificates, ability to provide custom openssl path.  I estimate this to be out next month sometime.   I hope that fits with your project timeline.

**Comment by nettnikl** [comment]
Thank you for the quick response.
Next month sounds good for a release - for now, what branch can you recommend to look at for developing a demo?

**Comment by abhinavsingh** [comment]
@nettnikl Unfortunately, there is no current branch.  I believe once onto it, might take a few hours to carve out a developer level APIs for reverse proxy ecosystem.  Till then feel free to hack through it :). I'll try to gather various requirements that folks have added through several issues/discussions and try to encapsulate the same in the APIs

**Comment by abhinavsingh** [comment]
@nettnikl https://github.com/abhinavsingh/proxy.py/pull/1252 will add support for modifying the request object before the request gets routed.  Give it a try when you can.  Let me know if this isn't working as expected.  Best
