### ISSUE TITLE
WebServer

### ISSUE THREAD

**Issue by Bradly7412** [abhinavsingh/proxy.py#1175]
Is the webserver option only for localhost?

**Comment by abhinavsingh** [comment]
@Bradly7412 Looks like I missed this somehow.  No web server can be access from anywhere.  Use `--hostname 0.0.0.0` to start listening on all interfaces, this will allow access to web server from external hosts too.  Best.

See https://github.com/abhinavsingh/proxy.py#unable-to-connect-with-proxypy-from-remote-host for more info.
