### ISSUE TITLE
[Tunnel] Workaround for Proxy Over SSH Tunnel

### ISSUE THREAD

**Issue by gonnsuarez** [abhinavsingh/proxy.py#1212]
I have tried to use the feature Proxy Over SSH Tunnel with:

On the local machine that will be running proxy.py:
```
proxy --enable-ssh-tunnel \
    --tunnel-username username \
    --tunnel-hostname ip.address.or.domain.name \
    --tunnel-port 22 \
    --tunnel-remote-port 8899 \
    --tunnel-ssh-key /path/to/ssh/private.key \
    --tunnel-ssh-key-passphrase XXXXX
```

but when I test it with curl in the remote machine that has de ssh server running I get
```
$ curl -x 127.0.0.1:8899 http://httpbin.org/get
curl: (52) Empty reply from server
```
And in the local machine running proxy.py with --log-level d it says:
`transport._log:1874 - Ignoring message for dead channel`

**The workaround founded:**

In the exact same conditions, I founded that if in the local machine that will has the proxy.py running, one just launch separately:

in one terminal only the proxy.py server:
```
proxy --port 8899
```
an in another terminal the ssh tunnel with remote port forwarding:
```
ssh -i /path/to/private.key -v -R 9000:127.0.0.1:8899 -N username@ip.address.or.domain.name
```

it works perfect!
The proxy server running on the local machine is perfectly accesible in the remote machine on the port 9000 and the test:

```
curl -x 127.0.0.1:9000 http://httpbin.org/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.54.0"
  },
  "origin": "x.x.x.x, y.y.y.y",
  "url": "https://httpbin.org/get"
}
```
retrieves the expected public ip of the local machine instead of the remote

I think that I'm missing something when I try to use the first approach, there is a clear line in the documentation saying:
`remote server MUST be configured to proxy HTTP(s) requests through the forwarded port number e.g. :8900`
And maybe I'm not understanding how to do that.

I will appreciate some guidence in this in order to make a correct use of this amazing tool

**Version information**
 - Local machines runnning proxy.py server I've tried only with windows 10 that will be the OS of the clients using this.
 - On the remote ssh server side I've tried both windows 10 and linux (unraid 6.9.2 home server) with same results.

Let me know if more information is needed, I didn't wanted to extend too much on this first post but I want to contribute to this awesome project, so let me know what can I do in order to help.
Thanks to all developers working on the project,

Regards!
Gonzalo

**Comment by abhinavsingh** [comment]
@gonnsuarez Thanks for reporting this.  Your 2nd approach is actually what currently works.  But I don't intend to ship this feature in such a manner.

The reason 1st approach doesn't work out of box is because handled connection from remote machines are not treated the same as an incoming HTTP proxy request.   Core reason behind this is lack of proper file/socket object support in `paramiko`.  This prohibits us from using `paramiko` SSH channel within `proxy.py` core as socket objects.  I have a local branch which tries to achieve this.  I had some success in making it work, but I haven't had time to finalize and push this out.

Now that you have reported this, I think we have a reason to get this out soon.   I'll keep this open and try to ship as part of `v2.4.4` release.   Over the weekend, I'll jump onto my local branch and try to push this out for you to try.  I'll update this thread once done.

In gist, my idea is to allow

```
proxy --enable-ssh-tunnel \
    --tunnel-username username \
    --tunnel-hostname ip.address.or.domain.name \
    --tunnel-port 22 \
    --tunnel-remote-port 8899 \
    --tunnel-ssh-key /path/to/ssh/private.key \
    --tunnel-ssh-key-passphrase XXXXX
```

and this instance can work both as `tunnel` forwarding mechanism + vanilla `http proxy` that `proxy.py` provides out of box.

**Comment by gonnsuarez** [comment]
Thanks @abhinavsingh for quiclky answer this thread.

So, to sort out how it works, `paramiko` let you build from low level all the `TCP` interaction needed to create SSH connections, in this case, the `tunnel` without the need of e.g. openssh client installed in the machine, is that right? That's why you want to include this feature inside `proxy.py`, instead of being dependent of openssh?
It would be a great feature, thanks for taking this issue to review it soon, I will definitely try it. I'm not experienced in this networking matters but I want to learn more so let me know whatever I can do.

**Comment by gonnsuarez** [comment]
Hi @abhinavsingh, I'm wondering if maybe you were able to make some advance in this problem with paramiko and tunneling?
I've tried some workarounds with subprocess, pexpect, wexpect, and those kind of python modules and it's not easy to make a propper handling of the command outputs, specially errors. So I understand even more the importance of including these feature with paramiko instead of thinking that a simple use of subprocess.run() will solve the issue.
Let me know if there is a way I can help in this issue,
Thanks in advance

**Comment by gonnsuarez** [comment]
Founded that launching the reverse tunnel provided by this example in an independent Thread appears to work for now,

https://github.com/paramiko/paramiko/blob/main/demos/rforward.py

Not sure if it is the best solution, I will continue testing it

**Comment by abhinavsingh** [comment]
@gonnsuarez Totally.  You are correct.  One can simply perform a manual setup and use paramiko base examples to achieve the necessary result.  With respect to `proxy.py`, my idea was to not develop a standalone solution for tunnel.

For that to work, paramiko socket objects must be integrated with proxy.py core.  Unfortunately, proxy.py core is async while paramiko only provide support for file-like socket objects.   This results in a mismatch which can be solved code wise, I simply haven't found an elegant solution for it yet.

Wrt proxy.py, idea is that, on a running proxy.py, I'll be able to open new tunnel dynamically.  For that to work as expected, we must integrate paramiko's sync objects into proxy.py async lifecycle.

**Comment by abhinavsingh** [comment]
@gonnsuarez You can give `grout` try now which essentially replaces Proxy Over SSH Tunnel, which wasn't going to work successfully without a server side component.  See https://github.com/abhinavsingh/proxy.py?tab=readme-ov-file#grout-ngrok-alternative
