### ISSUE TITLE
why use benchmark can not work 

### ISSUE THREAD

**Issue by qq516249940** [abhinavsingh/proxy.py#1269]
**os**
VERSION="20.04.4 LTS (Focal Fossa)"
proxy 2.4.3
python3.8

**Describe the bug**
why use benchmark can not work.

**Describe the bug**
only this Info
```bash
root@ub-jack:~/proxy.py# ./benchmark/compare.sh > /tmp/compare.log 2>&1
root@ub-jack:~/proxy.py# tail  -f /tmp/compare.log 
CONCURRENCY: 100 workers, DURATION: 1m, TIMEOUT: 1sec
```

**Comment by arne-heil** [comment]
I only tried it on Ubuntu 22.04. 

```sh
git clone https://github.com/abhinavsingh/proxy.py.git
cd proxy.py
pip install -r benchmark/requirements.txt
```

- [install oha](https://lib.rs/crates/oha)
```sh
echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list
wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
sudo apt update
sudo apt install oha
```
- for additional benchmarks: uncomment https://github.com/abhinavsingh/proxy.py/blob/develop/benchmark/compare.sh#L96 until https://github.com/abhinavsingh/proxy.py/blob/develop/benchmark/compare.sh#L119
- run benchmark
```sh
./benchmark/compare.sh
```

**Comment by abhinavsingh** [comment]
Thank you @arne-heil for posting the solution.  Much appreciated 🗡️
