### ISSUE TITLE
cont: TLSV1_ALERT_UNKNOWN_CA alert when using self-signed certificates for examples

### ISSUE THREAD

**Issue by EpicBirb** [abhinavsingh/proxy.py#1292]
#1268

> nil I'll archive/delete the `master` branch as I no longer try to keep it upto-date. Sorry for the inconvenience. Happy it worked out for you :)
> 
> @EpicBirb could you also try with `develop` and confirm. Please re-open if issue still persists.

still not working with the same error
![image](https://user-images.githubusercontent.com/68750348/199336188-171fff31-d534-49fb-a3eb-4edbf1afdb8d.png)

**Comment by abhinavsingh** [comment]
@EpicBirb will be fixed by https://github.com/abhinavsingh/proxy.py/pull/1446
