### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by thwee-alchemist** [abhinavsingh/proxy.py#13]
I was just wondering how the request for information from another server should be formed when it reaches the proxy. Do I send a request to localhost:8899 and include a query=remote_address parameter, or just q=remote_address?

**Comment by abhinavsingh** [comment]
@thwee-alchemist Joshua, you must setup `localhost:8899` as HTTP / HTTPS proxy server in your OS/Browser/Application settings. Example, when using `curl`

$ curl -p localhost:8899 https://abhinavsingh.com
