### ISSUE TITLE
`DEFAULT_DATA_DIRECTORY_PATH` Should be configurable

### ISSUE THREAD

**Issue by brki** [abhinavsingh/proxy.py#1316]
`DEFAULT_DATA_DIRECTORY_PATH` is hardcoded to `~/.proxy`.

**Describe the solution you'd like**
`DEFAULT_DATA_DIRECTORY_PATH` is configurable via an option, for example `--data-directory=/opt/proxy.py/data`

**Comment by sunnyjocker** [comment]
have this issue too, there is a extra work need to do if running proxy.py in docker image with host user, the $HOME directory doesn't exist, so i have to create it manually

**Comment by abhinavsingh** [comment]
@brki Thank you for bringing this to highlight.

@sunnyjocker Can understand the scenario you described (running as host user) and having to do extra work when setting up proxy.py

Will get this out in next release. ETA end-of-month.

**Comment by abhinavsingh** [comment]
@sunnyjocker @brki Following PR fixes this, now you may pass `--data-dir` flag to customise it

- https://github.com/abhinavsingh/proxy.py/pull/1389
