### ISSUE TITLE
can't open the URL: https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/

### ISSUE THREAD

**Issue by csrgxtu** [abhinavsingh/proxy.py#1335]
hi, @abhinavsingh we can't access the following URL
https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/

<img width="830" alt="image" src="https://github.com/abhinavsingh/proxy.py/assets/5053620/dc5e1857-17c9-4a1e-9012-2f8f972ab8d5">

**Comment by abhinavsingh** [comment]
@csrgxtu Thanks for reporting this.   Looks like my payments for GCP halted after RBI changes their guidelines.   I likely missed their emails and looks like GCP has deleted my personal site VM/SQL instances now 🤦‍♂️. Opened a ticket with GCP, let's see if I can restore it back.

**Comment by stefan6419846** [comment]
It seems like at least the basic article has been archived: https://web.archive.org/web/20220710151045/https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/ If you want to see the image as well, you probably should use an older snapshot like http://web.archive.org/web/20200511105817/https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/

**Comment by abhinavsingh** [comment]
@stefan6419846 Sorry, my personal GCP project was deleted by Google and all my decades worth of blog is now gone :(.  I might have a copy of it somewhere, but at this point I am too lazy to bring it back up.   Happy that archives still gives us access to the old posts.
