### ISSUE TITLE
mime/related

### ISSUE THREAD

**Issue by johnnyleehammer** [abhinavsingh/proxy.py#1340]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a feature request.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abhinavsingh** [comment]
You have forgot to add details :).   Closing, please re-open or create a new one with details.
