### ISSUE TITLE
How to use it to intercept and manipulate requests??`

### ISSUE THREAD

**Issue by nandish486** [abhinavsingh/proxy.py#1349]
![image](https://github.com/abhinavsingh/proxy.py/assets/93249676/64a243e8-5d12-48f5-b468-05c725c8cf0e)

i want to get urls accessed, and want to check if the filter is in adblock rule, if yes, then that url must be blocked by sending 404 response.

please help me i am new to this pakage.

**Comment by abhinavsingh** [comment]
@nandish486 There is already some filtering/blocking plugins in the examples directory that you can use as a skeleton for your application.

**Comment by nandish486** [comment]
> @nandish486 There is already some filtering/blocking plugins in the examples directory that you can use as a skeleton for your application.

Sir can you show me file? Actually I wanna block keywords and many things in my whole network.
Just like https filtering at high speeds. Actually I am over it because of speed only cause mitm proxy is too slow even on local host.

**Comment by abhinavsingh** [comment]
@nandish486 You can find various examples here https://github.com/abhinavsingh/proxy.py?tab=readme-ov-file#plugin-examples  Please reopen if something ain't working right for you.
