### ISSUE TITLE
Forward http socks4 socks5 to local port and use

### ISSUE THREAD

**Issue by FreeM1ne** [abhinavsingh/proxy.py#1364]
I want to redirect a purchased proxy in the format of
type:ip:port:login:password
To the format
type:localhost:port

**Comment by abhinavsingh** [comment]
@FreeM1ne can you kindly elaborate more?   May be a diagram using `--->` and `<---` will help me understand better what you are after and offer a solution :D

**Comment by abhinavsingh** [comment]
Closing, please reopen with more context.
