### ISSUE TITLE
Generate root CA certificates for Windows

### ISSUE THREAD

**Issue by Stepman123** [abhinavsingh/proxy.py#1369]
Here https://pypi.org/project/proxy.py/#tls-interception says By default, proxy.py will not decrypt https traffic between client and server. To enable TLS interception first generate root CA certificates:
 make ca-certificates

But I get an error.
Python 3.9

![bug-proxy](https://github.com/abhinavsingh/proxy.py/assets/8846337/510f05a2-5839-40d1-b548-efe6398a4a26)

**Comment by abhinavsingh** [comment]
What command did you use to generate the certificate?  Can you please paste the full command.

**Comment by Stepman123** [comment]
> What command did you use to generate the certificate? Can you please paste the full command.

proxy --make ca-certificates (this is in the screenshot)
and also this one:
proxy make ca-certificates

**Comment by Stepman123** [comment]
![make](https://github.com/abhinavsingh/proxy.py/assets/8846337/9f41b075-dde4-4836-ae25-fd75bcaa5ede)

translate:
"make" is not internal or external
command, executable program, or batch file.

**Comment by abhinavsingh** [comment]
Indeed, `python make` is not a valid command and yes, you will need `make` installed on Windows to make this work.  Once installed, you can execute these commands as done by our Windows workflows too

https://github.com/abhinavsingh/proxy.py/blob/develop/.github/workflows/test-library.yml#L737-L739

Feel free to re-open iff issue still persists.  Thank you

**Comment by Stepman123** [comment]
> you will need `make` installed on Windows to make this work.

Which make is required?
I installed "pip install make" but I don't know how to run it. It seems this is not what is needed.
Then I installed make using chocolatey "choco install make" but:
![make cert](https://github.com/abhinavsingh/proxy.py/assets/8846337/a63f7a1c-0605-4af2-a876-fc5c08245f15)
