### ISSUE TITLE
Could not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by shray1** [abhinavsingh/proxy.py#143]
HI Abhinav, 
I installed using the command "sudo  pip3 install --upgrade proxy.py"
Now I get the following error on running it

shray@Shray:~$ proxy.py
  File "/home/shray/.local/bin/proxy.py", line 74
    DEFAULT_DISABLE_HEADERS: List[bytes] = []
                           ^
SyntaxError: invalid syntax

**Comment by mbatrawi** [comment]
add this to your .profile or .bashrc and it will work
alias python=python3
and reboot

**Comment by abhinavsingh** [comment]
You don't have python3 or not using it.  Before running proxy.py, make sure
u have python3.   Run python --version to check.

I feel setting alias is a wrong strategy.

You must instead:
1) create a python3 virtualenv
     python3 -m venv venv
2) activate virtualenv
     source venv/bin/activate
3) run proxy.py now

**Comment by abhinavsingh** [comment]
If you don't prefer creating a `virtualenv`, then either:

1) Explicitly use `python3` and `pip3` everywhere, or
2) As @mbatrawi suggested, setup your `python` to point to `python3`.  Downside is that:
    a) Now it forces `python3` for everything on the system
    b) You still need to alias `pip3` and dependent packages like `coverage3`, ...
