### ISSUE TITLE
Explicit proxy.py shutdown ability when started in embedded mode

### ISSUE THREAD

**Issue by bhysyq** [abhinavsingh/proxy.py#158]
I am trying to use embed proxy.py to my python script:
```
from proxy.main import main

if __name__ == '__main__':
  main([
    '--hostname', '::1',
    '--port', '8899'
  ])
```

but I can't find a way to stop the process unless I stop the script. My script called `acceptor_pool.shutdown()` function, but the port is open, and I believe the proxy is still running.

Is there an easy way to shut it down? Thanks!

**Comment by abhinavsingh** [comment]
Currently it is designed as you experienced, proxy.py will also shutdown
with your script.

But it's a new and interesting requirement.  Thank you.  Will keep this
issue open and see what can we do to make it more flexible for embedded
mode.

**Comment by bhysyq** [comment]
Thanks for reply, I am going to use Docker as temporary fix. Hope one day we can have shutdown feature for embedded mode. Thanks!
