### ISSUE TITLE
HTTP Basic Authentication support

### ISSUE THREAD

**Issue by csparpa** [abhinavsingh/proxy.py#16]
As per title: it would be useful to have such a feature

Great work, anyway!

**Comment by axpatito** [comment]
+1

**Comment by abhinavsingh** [comment]
I'll try to get the support in, if you already know of any fork/patch/implementation do let me know. Thank You!!!

**Comment by abhinavsingh** [comment]
Its been a while but if you folks get a chance, do test out the Basic authentication support added in https://github.com/abhinavsingh/proxy.py/commit/3269998cd534b4dbc5425351f9540affb5e3956b Thank You.
