### ISSUE TITLE
Support for embedding Proxy.py within Python tests

### ISSUE THREAD

**Issue by deeplook** [abhinavsingh/proxy.py#162]
I'm looking for a way to start a proxy programmatically inside test suites, but I could not find something related in the documentation, and proxy.py's own test suite or main entry points do not seem to have something like this in mind. If it can be easily used programmatically, it would be nice to document it.

**Comment by abhinavsingh** [comment]
There is support, but you'll have to use `develop` branch for your use case.

In `1.x`, `main` method still can be used to start `proxy.py` in embed mode, however, that function blocks.  In `2.x`, a `start` context manager was added.  PTAL and lemme know how it goes for your use case.  https://github.com/abhinavsingh/proxy.py#embed-proxypy

**Comment by deeplook** [comment]
This `start` context manager looks like it's tied to the CLI input from `argparse`, and seems to block, too. So maybe not there yet for me, but I can't spend more time on this and would likely start it from a thread, instead, or so, for now.

**Comment by abhinavsingh** [comment]
@deeplook Thanks for giving it a try.  Happy to make changes for seamless test integrations.

1. For your scenario, IIUC, you would like to setUp `proxy.py` on test startup and teardown when test finishes.  Correct?
2. As `proxy.py` is now running under embed mode, you would also like it to not `argparse` which can raise conflict or unexpected behavior, if your application and `proxy.py` end up parsing same flag.
3. `start` actually doesn't block, it will returns immediately, just like any other context manager.  Example:
    ```
    from proxy.main import start
    with start([.... flags here ...]):
        .... app logic here ....
    ```
    But unsure how `start` can help within a test case `setUp` and `teardown` methods.

I am leaving this open for now until we have smooth integration path.

**Comment by abhinavsingh** [comment]
@deeplook If you could paste an example scenario where you are trying to integrate `proxy.py` (e.g. a dummy test), will greatly help.  Thank you.

**Comment by abhinavsingh** [comment]
This [stackoverflow](https://stackoverflow.com/questions/8416208/in-python-is-there-a-good-idiom-for-using-context-managers-in-setup-teardown) answer is exactly what we are after, though it will require you to override `unittest.TestCase.run` method.  I'll add a sample test case in the repository for future references.

**Comment by abhinavsingh** [comment]
https://github.com/abhinavsingh/proxy.py/tree/develop#unit-testing-with-proxypy this should help out with unit testing using proxy.py :)  See example usage [test_embed.py](https://github.com/abhinavsingh/proxy.py/blob/develop/tests/test_embed.py) Feel free to re-open if something doesn't work out.  Thanks again for bringing this up.
