### ISSUE TITLE
Luis v2 integration in bot

### ISSUE THREAD

**Issue by subhans3tech** [abhinavsingh/proxy.py#18]
i am trying to integrate v2 of luis api in my bot but it not work the sample code is as below

var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());
var recognizer = new builder.LuisRecognizer('https://api.projectoxford.ai/luis/v2.0/apps/72556e01-956c-4784-a26d-b7fb3e00df7b?subscription-key=15f282c492514272a354088915b56321');
var intents = new builder.IntentDialog({ recognizers: [recognizer] });
 bot.dialog('/', intents); 
 intents.matches('TSUGGEST', [
      function (session, args, next) {
        var task = builder.EntityRecognizer.findEntity(args.entities);
		var task1=builder.EntityRecognizer.findEntity(args.entities,'builtin.number');
        if (!task1) {
            builder.Prompts.text(session, "Please tell article name");
        } else {
            next({ response: task1.entity });
        }
    },
    function (session, results) {
        if (results.response) {
            // ... save task
            session.send("Ok...  '%s' task.", results.response);
        } else {
            session.send("Ok");
        }
    }]);

**Comment by abhinavsingh** [comment]
What errors does proxy.py throw if you start it as:

`$ python proxy.py --log-level DEBUG`

**Comment by abhinavsingh** [comment]
Closing issue due to lack of further details. Feel free to re-open if necessary. Thank You.
