### ISSUE TITLE
HttpParser bug when content-length header is missing

### ISSUE THREAD

**Issue by froginwell** [abhinavsingh/proxy.py#20]
When the request method is POST, the content-length is not set and the post data is empty, the proxy will not reach HTTP_PARSER_STATE_COMPLETE. Maybe it's the standard of RFC. If it's not, the solution below is practical:

        if self.state == HTTP_PARSER_STATE_HEADERS_COMPLETE and \
        self.type == HTTP_REQUEST_PARSER and \
        self.method == b"POST" and \
        len(data) == 0:
            self.state = HTTP_PARSER_STATE_COMPLETE

**Comment by abhinavsingh** [comment]
Can confirm this bug, per IETF discussions here http://w3-org.9356.n7.nabble.com/POST-with-empty-body-td103965.html

```
a POST with no content-length and no body is equivalent to a POST with Content-Length: 0 and nothing following, as could perfectly happen when you upload an empty file for instance. The resource is determined by the URL and the server has to know how to handle the body, including if it's empty. I don't see the issue here in fact
```

**Comment by abhinavsingh** [comment]
Updated issue title to reflect that bug exists both for Http request and response parsing. Even servers can omit to send content-length field in the response. Added a test case to highlight the same in commit https://github.com/abhinavsingh/proxy.py/commit/14655aa022e8df345899b41cdc2ce0e2c709e37a#diff-f4bc68ff01eef7bed2f3a64cad7d37caR244 as HttpParser has no way to know whether more data should be expected.
