### ISSUE TITLE
Use select.epoll to bypass FD_SETSIZE limit imposed by select.select usage

### ISSUE THREAD

**Issue by knife-s** [abhinavsingh/proxy.py#21]
Hello, I'm new in python and I am using this proxy but I have a problem, when lots of requests are being performed the proxy stops working because of the file   @#descriptor error (**FD_SETSIZE** limit).

I was reading what this problem only happens with select.select() and a workaround or solution may be using select.epoll() instead of select.select() but I didn't know how to do this correctly.

Thanks

**Comment by abhinavsingh** [comment]
It's not complex but unfortunately epoll is not universal like select system calls i.e. they are not supported on all OS.  One option is to simply use an existing Python event loop library, but I like to keep `proxy.py` minus external dependencies.  Python3 has some internal modules which can provide cross-platform support, if someone is interested in hacking this up let me know :)

**Comment by knife-s** [comment]
> It's not complex but unfortunately epoll is not universal like select system calls i.e. they are not supported on all OS. One option is to simply use an existing Python event loop library, but I like to keep `proxy.py` minus external dependencies. Python3 has some internal modules which can provide cross-platform support, if someone is interested in hacking this up let me know :)

Hi again! :P.

Im still interested on it.

**Comment by normal-cock** [comment]
Have you tried `DefaultSelector` in `selectors` model?

**Comment by abhinavsingh** [comment]
@normal-cock I did had a look at it but didn't pursued back then mostly because `proxy.py` also supported `Python 2.7` version.  Now that we are only `Python 3+` compliant, it will be a good time to revisit [selectors](https://docs.python.org/3/library/selectors.html).  Another module I want to check is [asyncio](https://docs.python.org/3/library/asyncio.html)
