### ISSUE TITLE
Bad performance when download large files

### ISSUE THREAD

**Issue by MacroBull** [abhinavsingh/proxy.py#22]
The subprocess consume 100% CPU of  one core and memory grows to hundreds of megabytes, and the speed falls as low as 100kB/s .

**Comment by abhinavsingh** [comment]
@MacroBull [proxy.py wasn't built](https://abhinavsingh.com/proxy-py-a-lightweight-single-file-http-proxy-server-in-python/) to handle blob files, though it works pretty well with YouTube and other video streaming websites. What's the size of the file you are downloading?

**Comment by MacroBull** [comment]
I am using proxy.py to forward Qt download from official source to a mirror, the largest file should be about 300MB.
See https://github.com/MacroBull/proxy_for_qt_online_installer/commit/7a52453fd98b81a4803c9bd08f34cc1ed8bbd67d for modifications

**Comment by abhinavsingh** [comment]
Kindly sync with latest in develop branch and start proxy as:

```
proxy.py --server-recvbuf-size 1048576
```

Play with a value that suits your application. Above 1048576 == 1 MB.

A higher buffer size will provide more throughput at increased RAM during the download operation. See commit https://github.com/abhinavsingh/proxy.py/commit/31bd810b6510a2a342baefd696c67f48fbda9968 comments for more details.

Kindly let me know if you run into an issue. Thanks for reporting.
