### ISSUE TITLE
Question: How to forward requests through another https proxy?

### ISSUE THREAD

**Issue by daspri** [abhinavsingh/proxy.py#226]
I would like proxy.py to send requests through another remote HTTPS proxy where I modify the header before using that proxy (adding basic authentication).  Is there an example of how I can achieve this?  I can't figure out how to do it, maybe it is easy?

Example: All requests to my local proxy.py will then go through proxy https://1.2.3.4:443 , adding "Proxy-Authorization: Basic ..." header.  (must support https requests over this proxy as well)

**Comment by abhinavsingh** [comment]
Hi @daspri 

I think this should be possible with a plugin.  You will have to modify default proxy server behavior as necessary.  E.g. as first step, you don't want proxy server to connect to upstream server _(requested by user)_ but rather an upstream proxy.

https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/redirect_to_custom_server.py is a good example of how to modify upstream (host, port) that proxy server will connect to, you want this to be your proxy upstream servers.

Then, as in your original question, you want to preserve headers etc.  I recommend you to read through documentation of proxy plugin https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/proxy/plugin.py  It will help you understand how different callbacks in a plugin can modify underlying behavior.

Example, `handle_client_request` where you want to preserve auth headers before queuing the packet to you proxy upstream server.

<img width="570" alt="Screen Shot 2019-12-09 at 3 13 41 PM" src="https://user-images.githubusercontent.com/126065/70481026-29631f80-1a96-11ea-8eaf-6d1aa5663850.png">

BTW, does this feature help solve your problem without running a central router proxy https://github.com/abhinavsingh/proxy.py#proxy-over-ssh-tunnel  Note that, this is still a development feature, so may not work as documented.

**Comment by daspri** [comment]
Hi,
I have looked at the redirect_to_custom_server, but the "request.set_url(UPSTREAM_SERVER)' would redirect TO the proxy server, rather than THROUGH the proxy server as I understand it.  I need to send all of the user's requests (both http and https) through this CONNECTed second https://proxy:port server.  I've been using the perl HTTP::Proxy module for this, but I would like to switch. 

I will inject a new Proxy-Authorization header into the connection to the https proxy server (the user does not send it). 

I do not have ssh access to the second proxy server.

**Comment by abhinavsingh** [comment]
I added a sample plugin, please use it as a base :)  Left enough comments in plugin code to help you understand what and why.  Let me know how it goes.

Start here and use latest develop branch:

https://github.com/abhinavsingh/proxy.py#proxypoolplugin

**Comment by daspri** [comment]
Thank you.  I will try it.

Just one question:  Is there an ssl version of "new_socket_connection" to connect and tunnel through the https proxy (requires ssl), or another correct way to handle ssl?

**Comment by daspri** [comment]
I guess that is a rather direct way of saying to manually wrap the socket.

BTW, I don't think you meant "bytes(request.port)" of an int, which returns an array of null bytes.
```
return (
            request.url.scheme +
            COLON + SLASH + SLASH +
            request.host +
            COLON +
            bytes(request.port) +
            request.path
)
```

**Comment by abhinavsingh** [comment]
You can use standard Python libraries or even 3rd party libraries in your
plugin to establish TLS connections.

Port is probably None because port is not set, which can happen if URL had
no port e.g. http://site.com.  Simply omit port in reconstruction or use
DEFAULT_HTTP_PORT when absent.   Happy to see a PR that fixes the example
plugin :)

Best
Abhinav

**Comment by daspri** [comment]
Since most of the web is https, I think the bigger issue is that it doesn't work with https.  For example, request.url.scheme is blank.  As it is, the "tunnel" function just sends the text request string, but it would need to ssl CONNECT securely through the existing tunnel and then do the request.   I'm not sure how to accomplish that.

**Comment by abhinavsingh** [comment]
That is incorrect, data is not being sent as text, `tunnel` function simply tunnel i.e. it doesn't cares about data being exchanged.

**Comment by daspri** [comment]
I am not as familiar with proxy.py as you are.  I have spent some unsuccessful hours trying to get it to work with https.   

curl -x http://127.0.0.1:8899 "https://github.com/about"

From the plugin: 
request.path =  
b'github.com:443'
request.url = 
SplitResultBytes(scheme=b'', netloc=b'', path=b'github.com:443', query=b'', fragment=b'')

I can't find where the path "/about" is available to the plugin.

I can send the 'CONNECT github.com:443 HTTP/1.1', through the proxy and must then wait to receive the 'HTTP/1.1 200 Connection established'  but how to wait and send another request for the path "/about"?
