### ISSUE TITLE
How to enable HTTPS redirection using redirect_to_custom_server plugin?

### ISSUE THREAD

**Issue by Benouare** [abhinavsingh/proxy.py#234]
Regarding the *MASTER* branch and the plugin_examples.py

**Describe the solution you'd like**
I would like, for example, to force make a redirection when a client is trying to connect to http(s)://bing.com will be redirected to http://google.com 
I would like to use something as : 
```
if self.request.host == "bing.com":
       self.request = proxy.makeRedirect("https://google.com")
```
I dont want to brake the HTTPS (so no MITM kind of stuff), i want to "block" the https, and force the redirection to google.com. 

I tried with the header "Location : http://google.com", but its seems not working. 

What I have currently done is that:  
```
if self.request.host != b"google.com":
            self.client.queue(proxy.build_http_response(
                307,
                headers={
                    # b'Content-Type': b'text/plain;charset=UTF-8',
                    b'Location': b'https://google.com',
                    b'Connection': b'close'
                    #    b'Host': b'www.bing.com'
                }
            ))
```
Regarding curl : 
`curl -v -L -x http://localhost:8899 "https://bing.com"`
```
(venv) iMac-de-Benoit:proxy.py benoit$ curl -v -L -x http://localhost:8899 "https://bing.com"
* Rebuilt URL to: https://bing.com/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8899 (#0)
* Establish HTTP proxy tunnel to bing.com:443
> CONNECT bing.com:443 HTTP/1.1
> Host: bing.com:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=www.bing.com
*  start date: Apr 30 20:48:00 2019 GMT
*  expire date: Apr 30 20:48:00 2021 GMT
*  subjectAltName: host "bing.com" matched cert's "bing.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc1a2009c00)
> GET / HTTP/2
> Host: bing.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 301 
< cache-control: private
< content-length: 193
< content-type: text/html; charset=utf-8
< location: https://www.bing.com:443/?toWww=1&redig=190A2EF713EF4400842E108F67079B2D
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-msedge-ref: Ref A: 23B25B2632694C88A8E0175402FD581B Ref B: PAR02EDGE0319 Ref C: 2019-12-19T14:39:16Z
< set-cookie: _EDGE_S=F=1&SID=2466BB468BD660442D81B5718A3061E9; path=/; httponly; domain=bing.com
< set-cookie: _EDGE_V=1; path=/; httponly; expires=Tue, 12-Jan-2021 14:39:16 GMT; domain=bing.com
< set-cookie: MUID=0F760647204560A22EE2087021A361B9; path=/; expires=Tue, 12-Jan-2021 14:39:16 GMT; domain=bing.com
< set-cookie: MUIDB=0F760647204560A22EE2087021A361B9; path=/; httponly; expires=Tue, 12-Jan-2021 14:39:16 GMT
< date: Thu, 19 Dec 2019 14:39:16 GMT
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'https://www.bing.com:443/?toWww=1&redig=190A2EF713EF4400842E108F67079B2D'
* Found bundle for host www.bing.com: 0x7fc1a151fca0 [can multiplex]
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8899 (#1)
* Establish HTTP proxy tunnel to www.bing.com:443
> CONNECT www.bing.com:443 HTTP/1.1
> Host: www.bing.com:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 301
< Location: https://google.com
< Connection: close
< Proxy-Connection: Keep-Alive
< Host: google.com:443
< 
* Received HTTP code 301 from proxy after CONNECT
* Closing connection 1
curl: (56) Received HTTP code 301 from proxy after CONNECT
```
That's look pretty good. 
But with the browser, that display nothing : I have kind of error as "Connection failed". 
What I am missing?

**Describe alternatives you've considered**
I tried with RedirectToCustomServerPlugin,  with HTTP & HTTPS, building the request with, del_header, add_header, changing the self.request.url/host/method. 
I ve tried with self.client.queue(proxy.build_http_response), but it looks like it's not working.

I thought i "just" have to change the headers of the my request (not the response) to block it, and to change it to make the redirection to the google website, but i dont know how to.  

To detect the "host", that's ok, it's done with FilterByUpstreamHostPlugin behavior. 

That's i possible in the master branch, or should i use the develop version?

**Comment by abhinavsingh** [comment]
@Benouare In the logs above, notice towards the end `curl: (56) Received HTTP code 301 from proxy after CONNECT`.  This is a problem from clients perspective `(e.g. curl, browsers)` because right before receiving `301` from proxy, client has established a SSL connection with upstream host (see `SSL certificate verify ok` log above).  So client was expecting encrypted data from upstream server, but it ended up receiving plain text `301 redirection` response. In short, you cannot modify SSL connection behavior without an active MITM.

**Comment by abhinavsingh** [comment]
@Benouare Closing this as this was more of a question.  Feel free to re-open if needed.

**Comment by Benouare** [comment]
Regarding my question, and your reply, I tried to use proxy.py with custom self generated certificate to be able to parse the data from the proxy client, to the remote server.

I tried with High Sierra, and Mojava, python 3.8. 
Below the different steps that I made : 
- generate ca by : `$ make ca-certificates` that generate the ca-key, ca-cert, ca-signing-key files -> OK 
- After that, I am starting, my server with : 
`$ sudo python3 -m proxy --ca-key-file ca-key.pem     --ca-cert-file ca-cert.pem     --ca-signing-key-file ca-signing-key.pem --log-level D`

The log bellow : 
```
2019-12-23 10:35:13,395 - pid:28404 [D] set_open_file_limit:489 - Open file soft limit set to 1024
2019-12-23 10:35:13,396 - pid:28404 [I] load_plugins:519 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2019-12-23 10:35:13,397 - pid:28404 [I] listen:61 - Listening on ::1:8899
2019-12-23 10:35:13,401 - pid:28404 [D] start_workers:78 - Started acceptor#0 process 28407
2019-12-23 10:35:13,405 - pid:28404 [D] start_workers:78 - Started acceptor#1 process 28408
2019-12-23 10:35:13,410 - pid:28404 [D] start_workers:78 - Started acceptor#2 process 28409
2019-12-23 10:35:13,416 - pid:28404 [D] start_workers:78 - Started acceptor#3 process 28410
2019-12-23 10:35:13,418 - pid:28404 [I] start_workers:84 - Started 4 workers
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
OSError when wrapping client
```

In server.py i see : 
```
if self.request.method == httpMethods.CONNECT:
            self.client.queue(
                HttpProxyPlugin.PROXY_TUNNEL_ESTABLISHED_RESPONSE_PKT)
            # If interception is enabled
            if self.flags.tls_interception_enabled():
                # Perform SSL/TLS handshake with upstream
                self.wrap_server()
                # Generate certificate and perform handshake with client
                try:
                    # wrap_client also flushes client data before wrapping
                    # sending to client can raise, handle expected exceptions
                    self.wrap_client()
                except OSError:
                    logger.error('OSError when wrapping client')
                    return True
                except BrokenPipeError:
                    logger.error(
                        'BrokenPipeError when wrapping client')
                    return True
                # Update all plugin connection reference
                for plugin in self.plugins.values():
                    plugin.client._conn = self.client.connection
                return self.client.connection
```

I thought that it was the method wrap_client() that raise the error but, when I tried to add some logs in it (as `logger.debug("HERE")`), i saw nothing. But if i am adding logs in the `except OSError:` i am seeing it well. 
So, the issue looks like to be in the wrap_client, but dont really know where.

**Comment by abhinavsingh** [comment]
@Benouare First thing first, any reason why you start proxy with `sudo`?  I generally don't recommend running under sudo unless necessary due to underlying system constraints.

Regarding MITM, `wrap_client` is most likely failing because generated certificates don't meet the MacOS minimum requirements.  I fixed this sometime back in https://github.com/abhinavsingh/proxy.py/pull/160 but never updated Makefile to utilize `pki.py` utility.  You can use it directly for now and generate compliant certificates.  Alternately, you can also use something like https://github.com/FiloSottile/mkcert

I have previously tested MITM with compliant certificates generated by `pki.py` utility.  I have reasons to believe default certificates generated by `Makefile` are no longer valid for macOS.

**Comment by abhinavsingh** [comment]
E.g.

```python
>>> from proxy.common import pki
>>> pki.generate_private_key(....)
```

See methods definition for valid arguments.

**Comment by Benouare** [comment]
> @Benouare First thing first, any reason why you start proxy with `sudo`? I generally don't recommend running under sudo unless necessary due to underlying system constraints.

About that : 
That was because, the proxy is generating/storing the certificates in  /Users/my_user/.proxy/
If i am running without the sudo, it looks like it's not allowed to generate/store and read the client certificates in this path. 
I will try to make it readable by my python daemon.

> 
> Regarding MITM, `wrap_client` is most likely failing because generated certificates don't meet the MacOS minimum requirements. I fixed this sometime back in #160 but never updated Makefile to utilize `pki.py` utility. You can use it directly for now and generate compliant certificates. Alternately, you can also use something like https://github.com/FiloSottile/mkcert
> 
> I have previously tested MITM with compliant certificates generated by `pki.py` utility. I have reasons to believe default certificates generated by `Makefile` are no longer valid for macOS.

Ok for the pki.py tool. I will try this asap and give u some feedback. Thx for your reply.

**Comment by Benouare** [comment]
Hi,
A little feedback.
When is said that is not working with the make ca-certificates is working fine. I Forget to add the ca-cert.pem in my firefox browser.  My apologies about that...

After that, when I tried to browse some websites, it's pretty working well. But i am still having this error : SEC_ERROR_REUSED_ISSUER_AND_SERIAL. 

As u can see, for I tried 2 website, the first one appears "badly", and the second one appears in the in a better way. 

![Capture d’écran 2020-01-06 à 18 38 08](https://user-images.githubusercontent.com/28023340/71836573-8dd4c700-30b4-11ea-975c-f282797c7d43.png)
![Capture d’écran 2020-01-06 à 18 41 47](https://user-images.githubusercontent.com/28023340/71836574-8e6d5d80-30b4-11ea-9e3d-780547ae88f1.png)

So, for me the browser is arguing that I have already the website certificate, and it doesn't match the current one. How is it possible? 
Is it possible to dont store the websites certificates, currently they are saved in the .proxy.py/certificates/ path ? 

Regarding your idea to use the pki functions.
First, i didnt succeed to work with it because of the passphrase. 
I just saw that there is in the api the function to remove it. 
I just tried with certs generated with pki functions : it's working a little bit better than with the direct openssl certificates generation, but still have some requests that are blocked because of SEC_ERROR_REUSED_ISSUER_AND_SERIAL

With the mkcert : I tried to work with it, but I didn't succeed yet... 

Finally, about the sudo, my .proxy/ folder was owned by root. I changed it to my user. So now it's working well without the sudo. 


To generate my certificate : 
```
pki.gen_private_key("key-private.pem", "password")
pki.gen_public_key("key-public.pem", "key-private.pem","password", "/CN=localhost")
pki.remove_passphrase("key-private.pem", "password", "key-private-2.pem")
```
To start : 
`python3 -m proxy --ca-key-file key-private-2.pem  --ca-cert-file key-public.pem --ca-signing-key-file ca-signing-key.pem`

**Comment by abhinavsingh** [comment]
Awesome, great to see it working e2e for you :)

I haven't seen `SEC_ERROR_REUSED_ISSUER_AND_SERIAL` before but quick googling surfaced this https://support.mozilla.org/en-US/kb/Certificate-contains-the-same-serial-number-as-another-certificate  There are some remedies here to remove existing browser certs, have you tried it already?

**Comment by abhinavsingh** [comment]
> To generate my certificate :
> 
> ```
> pki.gen_private_key("key-private.pem", "password")
> pki.gen_public_key("key-public.pem", "key-private.pem","password", "/CN=localhost")
> pki.remove_passphrase("key-private.pem", "password", "key-private-2.pem")
> ```

Happy to see a PR updating Makefile ca-* commands with what you discovered :)  If you could also update https-* commands, will be wonderful.  Thank you!!!
