### ISSUE TITLE
ProxyPoolPlugin.rebuild_original_path wrongly build request.port

### ISSUE THREAD

**Issue by hataketsu** [abhinavsingh/proxy.py#247]
**Describe the bug**
Build request.port in to list of zero instead of binary string. Eg: if port is 80 then build to b'\x00'*80 instead of b'80' 
 
**Version information**
 - Python 3.7
 - proxy.py 2.0

**Screenshots**
![image](https://user-images.githubusercontent.com/6312004/71546290-ff7f8780-29c7-11ea-8686-39ff9f89d8b3.png)

**Comment by abhinavsingh** [comment]
@hataketsu Thanks for reporting it.  This one is a known bug but I never went back to fix it.  See https://github.com/abhinavsingh/proxy.py/issues/226#issuecomment-564159678 for background.  Happy to see a PR towards fixing this.  Thank you!!!

**Comment by abhinavsingh** [comment]
@hataketsu I took a look, here within `rebuild_original_path` method, `port` is being used https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/proxy_pool.py#L82

Does explicit handling for `port=80` case in this method fixes the issue, can you please try?  Thank you.

**Comment by hataketsu** [comment]
I just fix it with `str(request.port).encode()`

**Comment by abhinavsingh** [comment]
👍👌

**Comment by abhinavsingh** [comment]
@hataketsu Will appreciate if you can send a PR addressing the same. Thank you

**Comment by abhinavsingh** [comment]
For anyone visiting this issue @paul-alkhimov also has a fix here https://github.com/paul-alkhimov/proxy.py/commit/55b9ef5dcf55dd54d962213d6c2e1c5090194f40
