### ISSUE TITLE
how to store proxy flow to mysql, can give me some tips, thanks

### ISSUE THREAD

**Issue by djerrystyle** [abhinavsingh/proxy.py#253]

**Comment by abhinavsingh** [comment]
Hi @djerrystyle can you expand what "store proxy flow in mysql" mean for you?  Thank you!!!

**Comment by djerrystyle** [comment]
Business functions base on many requests and api, i wanna store my footprint in Browser, and then go to the database, tag those requests, eg. Login function in web site base on check_username_is_exist request + CAPTCHA_request + Login_check_request.  after that , i can do some web security test, like Logical vul(login bypass), Besides i have a Compiled spider,after it spider a website , i can get the response from database, and regex to find what fingerprint in those page.   Elasticsearch,mongo is good,yet.

**Comment by abhinavsingh** [comment]
You should be able to write a `proxy.py` plugin to handle all incoming client requests.  This plugin of yours will be called for every client request, so in there you can choose to write into a MySQL database and / or Elastic, Mongo.

Pick any sample plugin, example https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/filter_by_upstream.py and tweak it for your needs.

**Comment by abhinavsingh** [comment]
@djerrystyle Closing this, please feel free to re-open if needed.
