### ISSUE TITLE
Chunk parser does not work

### ISSUE THREAD

**Issue by lxylxy123456** [abhinavsingh/proxy.py#26]
If the data ends with the size without CRLF, this patch can prevent the parser from raising an error.

Test program:

    from proxy import *
    cp = ChunkParser()
    data1 = b'3\r\nabc\r\n4'
    data2 = b'\r\nabcd\r\n'
    cp.parse(data1)			# error
    # would be correct if do `cp.parse(data1 + data2)`

**Comment by abhinavsingh** [comment]
Thanks for sending in the pull request https://github.com/abhinavsingh/proxy.py/pull/27, can you add above example as a test case so that we can check your PR in. Thank You!!!

**Comment by abhinavsingh** [comment]
Fixed with commit https://github.com/abhinavsingh/proxy.py/commit/4fde72fd106ff90d34971be3c867ec056554661f
