### ISSUE TITLE
[ERR_INVALID_CHUNKED_ENCODING] MITM HTTP(s) Responses

### ISSUE THREAD

**Issue by Benouare** [abhinavsingh/proxy.py#264]
Hi,
So, I am working on changing things in a web page that is deciphered by the proxy.py.

In my custom plugin, I am basically using the `handle_upstream_chunk` and the `chunk` param. 
In my case, I want for example change the title of the page from `<title>Le Figaro - Actualité en direct et informations en continue</title>` to  `<title>My --- Le Figaro - Actualité en direct et informations en continue</title>`

To do that : 
```
obj = bytes(chunk)
obj = obj.replace(
            b'<title>', b'<title> My  --- ')
return memoryview(obj)
```
In this case, the title change well, but the html page can't be loaded. I recheck the format, and that's looks good. In other website, it's more or less the same problem. 
![Capture d’écran 2020-01-15 à 01 39 02](https://user-images.githubusercontent.com/28023340/72395253-1e587a80-3739-11ea-892e-fb2512a8aa8b.png)
![Capture d’écran 2020-01-15 à 01 39 12](https://user-images.githubusercontent.com/28023340/72395278-3c25df80-3739-11ea-90db-000a745b23b1.png)

Ok, it's rough, cause i am currently spying all the request as img, js files and others, and not only http page, but that normally it should works? no? 

If try to change a word, It working more or lesse : changing the word "Perceuse" to "Stuff" is 'working'. 

Does it exist a kind of security in the page/browser that can be able to detect that some one change something in the page during the transfer? 
The normal page of the website : 
![Capture d’écran 2020-01-15 à 02 08 24](https://user-images.githubusercontent.com/28023340/72396172-18b06400-373c-11ea-8503-c76cd174d164.png)

The altered page of the website : 
![Capture d’écran 2020-01-15 à 02 07 48](https://user-images.githubusercontent.com/28023340/72396177-1b12be00-373c-11ea-8024-08ca5c84e705.png)

What I want is : to be able to change **part** of the HTML, to be able to remove/replace text (As Perceuse -> Stuff), or add/change/remove html tags.

Cheers

Edit : 
I have a part of the reason : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection. It looks like the X-XSS-Protection is fired and block the loading of the website. 
Gonna try to pass throught it. 
Edit2 : 
Maybe related to ERR_INVALID_CHUNKED_ENCODING as : 
- https://stackoverflow.com/questions/27330997/getting-an-error-err-invalid-chunked-encoding-while-using-squid-proxy-in-chrom
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

**Comment by Benouare** [comment]
After analysing this issue, it happens when I am modifying the chunk and trying to rebuild the current chunk of data.  
It looks like I doing it in the wrong way, and that's corrupt the webpage. 

The work away is to force the request in HTTP 1, and to force data formatting to be plain text (no gzip and co).

**Comment by abhinavsingh** [comment]
Hi @Benouare Yes, as you discovered cross site scripting and MITM attacks can be detected in modern browsers to some extent.

Even if browser doesn't impose any problems, there are other things to take care. E.g.

1. **Content encoding**: gzip, ..... and what not. One way to tackle this would be to disable encoding altogether in requests so you don't have to deal with it when processing responses.

2. **Chunked encoding**: Same as above, most web servers like Nginx will send chunked encoded data by default (if client accepts it).

There are other things that can effect MITM but handling above two cases should get you covered for 90% of the cases.  Let me know.

**Comment by Benouare** [comment]
> Hi @Benouare Yes, as you discovered cross site scripting and MITM attacks can be detected in modern browsers to some extent.
> 
> Even if browser doesn't impose any problems, there are other things to take care. E.g.
> 
> 1. **Content encoding**: gzip, ..... and what not. One way to tackle this would be to disable encoding altogether in requests so you don't have to deal with it when processing responses.
> 2. **Chunked encoding**: Same as above, most web servers like Nginx will send chunked encoded data by default (if client accepts it).
> 
> There are other things that can effect MITM but handling above two cases should get you covered for 90% of the cases. Let me know.

Hi @abhinavsingh , 
it looks like in TLS decryption mode/mitm, the browser "see nothing". 
I thought that the browser was able to detect an MITM Attack, but it was because my chunk was corrupted, not because of an browser fonctionality.

With my last tests (request in HTTP 1, and identify as content-encoding) the browser is displaying all the webpage without any warnings or other alerts.  

About Cross site scripting, I didnt try yet, but it looks like if we change the headers response, we can disable the XSS protection. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

Again, thx for your replies.

**Comment by abhinavsingh** [comment]
@Benouare Awesome news.

Btw, jFYI, browser can detect MITM via mechanism like OCSP and certificate pinning.  Example, if you try to do similar MITM attack on youtube or other major sites, it will most like not work (please try and let me know if it works). Browser will detect and warn the user about suspected MITM attack.

Yes, one can disable this browser security feature. For Chrome, see [helper/chrome_with_proxy.sh](https://github.com/abhinavsingh/proxy.py/blob/develop/helper/chrome_with_proxy.sh)

**Comment by Benouare** [comment]
> Btw, jFYI, browser can detect MITM via mechanism like OCSP and certificate pinning. Example, if you try to do similar MITM attack on youtube or other major sites, it will most like not work (please try and let me know if it works). Browser will detect and warn the user about suspected MITM attack.

First, first for the information about OCSP, i will try to see more about that.
I just give a try ( with branch fix/certs-generation-chrome-issue + my own custom branch that inject some code) it looks like chrome doesnt see that I am currently adding **inline** js in the webpage. 
I gave a try on FB. 
Cheers
