### ISSUE TITLE
How can I access HTML Source from proxy.py?

### ISSUE THREAD

**Issue by shieldnet** [abhinavsingh/proxy.py#28]
How can I access HTML Source from proxy.py? 

I tried to print() data and buffer and body but failed to print any of them..

**Comment by abhinavsingh** [comment]
To achieve the same, one will have to modify core `proxy.py` file. I am thinking of adding a plugin API which would allow developers to selectively _(for some or all proxied URLs)_ access content _(body, headers etc)_ as it gets parsed.

However, I cannot guarantee an ETA for the same. Meanwhile, if you are happy to edit the core `proxy.py` file, consider printing out `body` attributes of request/response parsers. They can be found here https://github.com/abhinavsingh/proxy.py/blob/develop/proxy.py#L350-L351

**Comment by abhinavsingh** [comment]
@shieldnet PTAL at SaveHttpResponses plugin here  https://github.com/abhinavsingh/proxy.py/blob/develop/plugin_examples.py , this should get you started for saving HTML source.

PS: Remember that only works for HTTP requests, for encrypted HTTPS you will mostly only end up saving encrypted response on disk.  Marking this as closed, feel free to re-open or open a separate issue for further iterations.  Thank you.
