### ISSUE TITLE
How to store and share data between workers in read and write mode.

### ISSUE THREAD

**Issue by Benouare** [abhinavsingh/proxy.py#283]
Hi, 
The idea is that i want to load some "porn"/"warez"/"sect"&co blacklist domains (in squidguard format https://dsi.ut-capitole.fr/blacklists/) to have a big list of domains that proxy.py must block.
That list, could be quiet big.
If i am doing it directly in my custom plugin (in the constructor for example) it will be loaded at every request, and it will be really powerless. It could cost easily more than 1 second.
But, doing this in a singleton makes me sure that the loading process will be done just one time, at the first instanciation of my plugin, and not at each instanciation. 
```
def __init__(self, uid, flags, client, event_queue):
        super().__init__(uid, flags, client, event_queue)
        self.singleton = SingletonMemory()
```
With that trick, I am able to share data between requests during all the lifetime of the app.
I can retreive, **in a single worker**, this singleton everywhere I wanted to.
After i can do something as : 
```
request.host in self.singleton.PORN:
       self.blockUrl() # fake function just to illustrate
```

The main problem with that solution is, i must use the --num-workers flag, and set it to 1. If i am not doing it, i will have 4 workers (4 cpu on my system) and 4 singletons, one for each thread.

Questions : 
- this trick/solution does it looks good for you? 
- how can I share datas between workers/threads? I read something about queue (and tried to use your implementation in proxy.py, without success), but i dont know if that's the solution.

**Comment by abhinavsingh** [comment]
@Benouare You are on right track here w.r.t sharing data between multiple threads.

However, as you noticed, it can be tricky to share data across processes.  Just to recap, `proxy.py` by default work in threaded mode i.e. each worker process will spawn a new thread to handle client request. 

And yes, `proxy.py` event queue mechanism can be re-used to share data between processes. However, unsure if it will provide any significant benefit for your use case.  You really don't need any cross-process communication.

So with that in mind, singleton model is good.  E.g. with N=4, you will have 4 singletons maintained across 4 worker processes.  Internally, a singleton gets re-used by all request served by particular worker process.

You might want to have a single singleton maintained for all worker process.  Can be achieved but will require more work e.g. check `multiprocessing.Manager` and its data structures, give it a shot and see if it works for you.  IIUC, you only want a read-only copy shared across processes, which should be possible without running into lock contentions.

**Comment by abhinavsingh** [comment]
Re-open if necessary.

**Comment by Benouare** [comment]
As usual, thx for the detailed reply. 
As i though, i must digg in Queues. 
Currently, in a WebServerPlugin (not a ProxyPlugin), I am able to get the singleton and to update some data that are in it. After that, I able to read it in the ProxyPlugin side to change the proxyplugin behavior. 
With one worker/thread => No issue it works well, but as you already know with multiple threads (=multiple singleton) I will just have one singleton that will be updated, and not all the singleton...
