### ISSUE TITLE
proxy.py seems to ignore /etc/hosts

### ISSUE THREAD

**Issue by sjlawsonAL** [abhinavsingh/proxy.py#29]
When configuring a browser to use proxy.py, domain names defined in /etc/hosts do not work. I think that's a common issue with a lot of local proxies. It may seem superfluous, but it would be really useful for automated testing of web applications. How might one add that feature?

**Comment by abhinavsingh** [comment]
@sjlawsonAL DNS resolution happens locally, so ideally `/etc/hosts` entries shouldn't be an issue. Below is what I tried on my Macbook:

1) Define a domain named `proxy.py` within `/etc/hosts`
```
$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 

127.0.0.1       proxy.py
```

2) Start a HTTP server serving `proxy.py` domain on port 8000
```
$ cd /tmp && mkdir proxy.py && cd proxy.py
$ touch index.html
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

3) Access `proxy.py:8000` using curl:
```
$ curl -x http://127.0.0.1:8899 http://proxy.py:8000
<html>
<head></head>
<body>
    <h1>Proxy.py</h1>
</body>
</html>
```

Are you trying to achieve something similar? If not, kindly elaborate what you tried and also provide few details about your environment _(OS, proxy.py version etc)_.

**Comment by sjlawsonAL** [comment]
proxy.py v0.3
MacOS High Sierra, Darwin Kernel Version 17.7.0
I'm experimenting with the use of proxy.py as a replacement for browsermob proxy, with Selenium & webdriver.

I'm using proxy.py to intercept calls to an analytics platform, api.segment.io, and redirecting those calls to an instance of Mountebank where the requests can be analysed and tested using a Selenium framework. I'm really, really close - it kind of works when the browser is connecting an external web server, but when I tried it on a local VHOSTed url, proxy.py couldn't connect.

**Comment by abhinavsingh** [comment]
You can try to ping the domain locally and check the IP it resolves to. Example:

If the incoming request is for URL `http://mountebank.local`, then `ping mountebank.local` must resolve to IP address mapped under `/etc/hosts`.  As I verified in https://github.com/abhinavsingh/proxy.py/issues/29#issuecomment-446323588, `proxy.py` will respect entries in `/etc/hosts` file.

I believe this issue is not related to `proxy.py` but just a local setup issue. Lemme know.

**Comment by sjlawsonAL** [comment]
That's very good news. I'll keep digging. Thanks!
