### ISSUE TITLE
Server Sent Events(SSE) support via proxy.py

### ISSUE THREAD

**Issue by ahmedtalhakhan** [abhinavsingh/proxy.py#290]
**Check FAQs**

**Is your feature request related to a problem? Please describe.**
Proxy.py supports websockets but the usage of Server Sent Events(SSE) is growing tremendously. Proxy.py should try to support SSE via EventStream protocol in both proxy and Webserver mode if possible.

**Describe the solution you'd like**
Support for SSE via EventStream protocol.

**Describe alternatives you've considered**
This is a potential feature request

**Additional context**

PS. I am more then willing to help add this support given some technical direction towards the easiest solution.

**Comment by abhinavsingh** [comment]
I think we already have all the necessary toolkit for SSE.

Example, it should be straightforward to port Mozilla's SSE PHP example into Python using proxy.py
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

If we just modify your example from #289 and add necessary headers, we have a SSE.  Wdyt?

**Comment by abhinavsingh** [comment]
@ahmedtalhakhan closing this down, feel free to re-open if SSE use case isn't working out as expected.  Thank you for bringing this up.
