### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by IzanLarumbe** [abhinavsingh/proxy.py#293]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a bug report.

**Describe the bug**
After using PIP + github to install proxy, it gave me this error:
![image](https://user-images.githubusercontent.com/48862659/74193717-26340d80-4c58-11ea-9bfb-32744f2501d5.png)

**To Reproduce**
Steps:
command line:
```
pip install git+https://github.com/abhinavsingh/proxy.py.git@master
```
then:
```
proxy
```
and it gave me this output:
![image](https://user-images.githubusercontent.com/48862659/74193785-46fc6300-4c58-11ea-9ffb-7a9ba6fcac45.png)

**Expected behavior**
Sucessfull run.
**Version information**
 - OS: [Linux Ubuntu ]
 - Browser [No browser]
 - Device: [Computer]
 - proxy.py Version [Lastest]

**Additional context**

**Screenshots**

**Comment by abhinavsingh** [comment]
Looks like either a process is already listening on 8899 or user don't have
right permissions to listen on a port.

Can you double check? This is unrelated to proxy.py

Thank you

**Comment by IzanLarumbe** [comment]
Did double check, i guess it works now.

Thank you
