### ISSUE TITLE
[ReverseProxyPlugin] Add support for https use case

### ISSUE THREAD

**Issue by atsakiridis** [abhinavsingh/proxy.py#295]
**Is your feature request related to a problem? Please describe.**
Not really a problem just some functionality that would make the reverse proxy use case more complete. 

**Describe the solution you'd like**
Right now it's only possible to use cleartext http between proxy and upstream server. Would be nice to also be able to support https for cases where upstream uses it. We can enhance reverse_proxy.py to establish a secure connection in case the proxy pass url uses https.

**Additional context**
Related discussion can be found [here](https://github.com/abhinavsingh/proxy.py/issues/292#issuecomment-586738404)

**Comment by abhinavsingh** [comment]
@atsakiridis 

PTAL at https://github.com/abhinavsingh/proxy.py/pull/675
