### ISSUE TITLE
Update documentation to remove support for 3.5.x

### ISSUE THREAD

**Issue by dagwieers** [abhinavsingh/proxy.py#317]
**Describe the bug**
The documentation indicates proxy.py should work on Python 3.5+, but it gives a **SyntaxError: invalid syntax** message when run on Python 3.5.9.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/proxy/__init__.py", line 11, in <module>
    from .proxy import entry_point
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/proxy/proxy.py", line 32
    self.acceptors: Optional[AcceptorPool] = None
                  ^
SyntaxError: invalid syntax
```

**To Reproduce**
1. Run `proxy.py` using python 3.5.9
2. See error

**Expected behavior**
Working on Python 3.5.9

**Version information**
 - OS: Ubuntu latest (GitHub CI)
 - proxy.py Version 2.1.2

**Comment by abhinavsingh** [comment]
Did you install it using *pip*?

If not, please also install packages from *requirements.txt*

Thank you
------------------------------------------------------
Abhinav Singh,
https://abhinavsingh.com
------------------------------------------------------

**Comment by dagwieers** [comment]
@abhinavsingh Yes, while we are pulling from our own requirements.txt for testing using proxy.py (including typing-extensions), we get the above issue. Here is a direct link to the CI failure: https://github.com/dagwieers/plugin.video.vrt.nu/runs/530145072

It works fine for the Python 3.6, 3.7 and 3.8 targets.

**Comment by abhinavsingh** [comment]
Thank you for the context.  Will be digging into it this week.

------------------------------------------------------
Abhinav Singh,
https://abhinavsingh.com
------------------------------------------------------

**Comment by abhinavsingh** [comment]
Looks like this is an issue we ran previously with `Python 3.5`.  In `proxy.py 2.1.2` Python version guards were added to `setup.py`.  So `2.1.2` must fail to install on unsupported versions.

<img width="263" alt="Screen Shot 2020-03-24 at 8 13 32 PM" src="https://user-images.githubusercontent.com/126065/77438540-f60d8c00-6e0b-11ea-8aec-42a25dfea3ea.png">

It's interesting too because when I started adding typing support to `proxy.py`, `Python 3.5` was one of the supported version.  But as mainstream changes were poured into older Python version, `3.5` stopped working.  It should still work for older versions of `3.5.x` but not `3.5.9`

**Comment by abhinavsingh** [comment]
Closing this issue as porting back at this point will be too much of a work.  If you simply need basic `proxy.py` features, consider using `1.x` series which had no typing annotations.

Also do check this https://github.com/abhinavsingh/proxy.py#syntaxerror-invalid-syntax

Thank you!!!

**Comment by dagwieers** [comment]
No problem. I was reporting this because what was advertised didn't work. I was planning to exclude proxy.py for Python 3.5 anyway in CI as we do now for Python 2.7. So don't spend any breathe on this ;-)

But maybe it is safer to remove Python 3.5 from the support matrix/documentation?

**Comment by abhinavsingh** [comment]
Support matrix was updated with `2.1.2.   Please do point out if it was not updated somewhere.  Happy to address it.

<img width="180" alt="Screen Shot 2020-03-24 at 8 21 55 PM" src="https://user-images.githubusercontent.com/126065/77439532-2f92c700-6e0d-11ea-9b64-79c10559048a.png">

**Comment by dagwieers** [comment]
Ok, I thought I remembered seeing it on the README, but it must have been the below section that must have confused me:

https://github.com/abhinavsingh/proxy.py/blob/develop/README.md#syntaxerror-invalid-syntax

> Hence a Python version that understands typing annotations is required. Make sure you are using `Python 3.5+`.

and

> It will enable `proxy.py` to run on Python `pre-3.5`, even on `2.7`. However, as all future versions of Python will support `typing annotations`, this has not been considered.

**Comment by abhinavsingh** [comment]
Aah, thanks a ton for pointing this out.  This is just another proof that it worked for early versions of `3.5` but not for newer minor releases.  Re-opening and repurposing to address the same.

**Comment by dagwieers** [comment]
No worries, thanks for proxy.py and the great support!
