### ISSUE TITLE
[MITM] Changing response body

### ISSUE THREAD

**Issue by grvhi** [abhinavsingh/proxy.py#332]
First off, thanks for a great library! 

I've successfully implemented a basic MITM proxy with TLS. However, I'm trying to work out how to efficiently parse the response from the upstream server, inspect the contents and change the data being sent downstream to the original requester.

For example, the requester is attempting to download a JSON file as octet/binary; I want to catch the response and add fields to the JSON being returned. As soon as I make changes to the JSON data, the response to the client hangs or the JSON data is truncated. I suspect I'm doing something wrong with the ``HttpParser`` as the value of ``parser.body`` is always ``None``.

What I'm seeing though makes sense as the length of the body I'm returning is longer (rather, different) to the value of the Content-Length header; I need to change that value, but the headers and the JSON data are being returned in two different chunks.

Is there another way to create a plugin which achieve this?

**Comment by abhinavsingh** [comment]
Thank you @grvhi .  This should be possible though I haven't tried it yet myself.  You are likely also gonna run into other issues than just `content-length` header changes.  Example, website might be using `Subresource Integrity` and changing content of the file will fail the integrity test.

You can fork/extend [base.py](https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/cache/base.py#L49-L56) from `cache_responses` plugin.  Here you should modify headers within `handle_client_request` and then modify body within `handle_upstream_chunk`.

Please let me know how it goes. Cheers!!!

**Comment by grvhi** [comment]
Thanks @abhinavsingh. This for an API, so no website/browser issues, thankfully. I’ve tried modifying the body in ``handle_upstream_chunk`` but the issue is that the headers in the upstream response are contained within a separate chunk. The headers come in the first chunk, then the data in another chunk; this means I don’t know how big my response will be at the moment I’m dealing with the headers chunk. 

Is there a method where I can capture all the chunks in a response before returning any chunks to the client?

**Comment by abhinavsingh** [comment]
You can accumulate all chunks in-memory and dispatch the response in one go within [on_upstream_connection_close](https://github.com/abhinavsingh/proxy.py/blob/dfea68cf7a29b1b3688a87c8785025bef40ce6a7/proxy/http/proxy/plugin.py#L75-L86) callback.

**Comment by grvhi** [comment]
Much appreciated, thanks @abhinavsingh - I’ll try that.

**Comment by abhinavsingh** [comment]
> You can accumulate all chunks in-memory and dispatch the response in one go within [on_upstream_connection_close](https://github.com/abhinavsingh/proxy.py/blob/dfea68cf7a29b1b3688a87c8785025bef40ce6a7/proxy/http/proxy/plugin.py#L75-L86) callback.

This approach assumes each client connection will be used only for a single request-response cycle.  Ideally, same connection can be used for multiple HTTP requests.  Even worst, upstream server may decide not to close connection due to `keep-alive` settings.

Hence, alternately, you can accumulate `content-length` worth of data in memory and then modify/dispatch modified response to the client from within `handle_upstream_chunk`.

**Comment by grvhi** [comment]
@abhinavsingh - I've been testing a few implementations based on what you've said above, but I haven't been able to work out how to prevent ``handle_upstream_chunk`` from returning data to the client; ``handle_upstream_chunk`` requires a return value of type ``memoryview`` and there doesn't seem to be a neat way of preventing this chunk from ultimately being returned to the client...?

Basically (and noting your caveats on the connection-reuse issue), I can't work out how to "accumulate all chunks in-memory and dispatch the response in one go" as it seems that ``handle_upstream_chunk`` requires each chunk to be returned, which is then flushed to the client.

**Comment by abhinavsingh** [comment]
Yep `handle_upstream_chunk` expects a response which is then sent to the client.  But how about you return an empty response from callback and maintain an in memory cache of all chunks received from upstream server.  Can you try the same.  Thank you.

**Comment by grvhi** [comment]
> Yep `handle_upstream_chunk` expects a response which is then sent to the client. But how about you return an empty response from callback and maintain an in memory cache of all chunks received from upstream server. Can you try the same. Thank you.

If I ``return memoryview(b'')`` within ``handle_upstream_chunk``, I get ``OSError when flushing buffer to client``

**Comment by abhinavsingh** [comment]
Can you share a snippet of your code for investigation.  Thank you!!!

**Comment by grvhi** [comment]
Thanks again for your help @abhinavsingh. Here's the v simple plugin I'm using:

```python
class ModifyResponseData(HttpProxyBasePlugin):
    """Modifies upstream server responses."""
    all_chunks = list()

    def before_upstream_connection(self,
                                   request: HttpParser) -> Optional[HttpParser]:
        return request

    def handle_client_request(self,
                              request: HttpParser) -> Optional[HttpParser]:
        return request

    def on_upstream_connection_close(self) -> None:
        print('CLOSING', self.all_chunks)
        # What to do here?

    def handle_upstream_chunk(self, chunk: memoryview) -> memoryview:
        self.all_chunks.append(chunk)
        return chunk
```

**Comment by anthonykgross** [comment]
I'm stuck at the same point. 

For the Cache plugin, what's the point to store chunks and never deliver them for the same given request ? I guess it's most a logging plugin instead of caching one :)

**Comment by abhinavsingh** [comment]
Thanks @anthonykgross for the message. Totally, without serving back the cached content, it will simply be a `CacheResponsesPlugin` plugin.  We already have a `CacheResponsesPlugin` which stores all chunks into a single cache file. See https://github.com/abhinavsingh/proxy.py/tree/develop/proxy/plugin/cache

@grvhi requirement here is slightly different compared to standalone `CacheResponsesPlugin`. He wants to:

1. Not only cache the responses but also modify the responses before dispatching to client
2. We already have a `ModifyPostDataPlugin` which `Modifies POST request body before sending to upstream server`. See https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/modify_post_data.py

IIUC, @grvhi only cares ability to modify response received by client _(@grvhi correct me if wrong)_

I did a quick prototype, check it here https://github.com/abhinavsingh/proxy.py/pull/342

**Comment by abhinavsingh** [comment]
Hi @grvhi @anthonykgross  I hope this issue is resolved now.  PR #342 demonstrate some of these aspects which can be customized for specific needs.  Please re-open this issue if needed.  Thank you!!!

**Comment by grvhi** [comment]
Thank you @abhinavsingh - this helps. Apologies for not replying sooner!
