### ISSUE TITLE
How to Solve HTTPS Connection Timeout

### ISSUE THREAD

**Issue by zhangshengchun** [abhinavsingh/proxy.py#34]
@abhinavsingh 
i use python requests like this:
res = requests.get(url='https://httpbin.org/ip', proxies={'http':'ip:port', 'https':'ip:port'}, timeout=10, verify=False), got a timeout error, python program get no response, but found proxy.py debug log info is ok. and if request http://httpbin.org/ip, it's fine.
then  i use internet explorer with the proxy, working correctly. It looks like a certificate problem when running in centos system. how to solve it.

**Comment by abhinavsingh** [comment]
Thanks for reporting. Sounds like the problem is peculiar to CentOS systems, correct? Unfortunately, I don't have one to try `proxy.py` out. Can you try and check if ca-certificates are installed on your system?
