### ISSUE TITLE
[Plugins] AttributeError: module 'proxy.plugin.cors' has no attribute '__mro__'

### ISSUE THREAD

**Issue by drzraf** [abhinavsingh/proxy.py#340]
**Describe the bug**
```
2020-05-16 20:10:25,296 - pid:23166 [I] load_plugins:519 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
Traceback (most recent call last):
  File "~/.local/bin/proxy", line 8, in <module>
    sys.exit(entry_point())
  File "~/.local/lib/python3.8/site-packages/proxy/proxy.py", line 89, in entry_point
    main(input_args=sys.argv[1:])
  File "~/.local/lib/python3.8/site-packages/proxy/proxy.py", line 80, in main
    with Proxy(input_args=input_args, **opts):
  File "~/.local/lib/python3.8/site-packages/proxy/proxy.py", line 31, in __init__
    self.flags = Flags.initialize(input_args, **opts)
  File "~/.local/lib/python3.8/site-packages/proxy/common/flags.py", line 254, in initialize
    plugins=Flags.load_plugins(
  File "~/.local/lib/python3.8/site-packages/proxy/common/flags.py", line 512, in load_plugins
    mro = list(inspect.getmro(klass))
  File "/usr/lib/python3.8/inspect.py", line 489, in getmro
    return cls.__mro__
AttributeError: module 'proxy.plugin.cors' has no attribute '__mro__'
```
**To Reproduce**
1. `sed s/ModifyPostDataPlugin/Cors/g modify_post_data.py > cors.py`
2. // Add `'CorsPlugin'` to `~/.local/lib/python3.8/site-packages/proxy/plugin/__init__.py`
3. `proxy  --plugins proxy.plugin.cors`

**Expected behavior**
Plugin loaded

**Version information**
 - OS: Ubuntu 20.04
 - proxy.py Version 2.1.2 (via `pip3 --user`)

**Additional context**
I first tried loading plugin from a non-pip path and tried symlinking... without success before fallback to just this simple test.

**Comment by abhinavsingh** [comment]
Hi @drzraf , thanks for reporting this.  Have you tried setting python path for non-pip path plugins.  See some example here https://github.com/abhinavsingh/proxy.py#unable-to-load-plugins

**Comment by abhinavsingh** [comment]
@drzraf Marking this as closed assuming issue has been resolved for you.  If problem persists, please re-open.

In general, to customize an existing plugin, you can simply follow:

1. `cp /path/to/existing/plugin.py /path/to/myapp/my_plugin.py`
2. Modify `my_plugin.py` as necessary.  Let's consider you name your plugin class as MyPlugin
3. Then run your plugin as `PYTHONPATH=/path/to/myapp proxy --plugins my_plugin.MyPlugin`

**Comment by drzraf** [comment]
Yes, it worked. I think the confusion came from the Python namespace convention. You may want to make clearer in the documentation that the expected syntax is `<name-of-the-file>.<name-of-the-class>`

**Comment by abhinavsingh** [comment]
Thank you, will update the doc to reflect the same.
