### ISSUE TITLE
[Plugins] Whitelist by IP

### ISSUE THREAD

**Issue by guysoft** [abhinavsingh/proxy.py#350]
**Is your feature request related to a problem? Please describe.**
I want to only let certain IPs access the proxy. 

**Describe the solution you'd like**
some flag such as ``--whitelist-ips=ip1,ip1,ip-range``

**Describe alternatives you've considered**
For now I did is add to ``def handle_readables(self, readables: List[Union[int, HasFileno]]) -> bool:`` in ``/proxy/http/handler.py``:
```
            if self.client.addr[0] != "192.168.0.1":
                self.client.closed = True
                return True
```

Is there a more elegant way to do this?

**Comment by guysoft** [comment]
Won't solve my issue. Need a dynamic way to whitelist IPs.

**Comment by guysoft** [comment]
Hey,
Closed it because I found that a dynamic list also requires me to write an external server that the machine that needs to use the proxy sends it a token to whitelist itself. Then I added the ``if`` statement above to a list that is parsed from a yaml file.

I would love to have that somehow get this out for others to use. But I seemed like a lot to ask in a in this issue so I closed it. I would gladly help figure out how to write a plugin that does that and contribute it back.

The code that I currently have for proxy.py is injected here:
https://github.com/abhinavsingh/proxy.py/issues/350#issue-623814939

How would I build a plugin around that?
If I can do that I can also release the flask webserver that I built that lets you use a token to add your IP to the whitelist. And package that as an example.

**Comment by abhinavsingh** [comment]
@guysoft Sure, let's have a plugin for it.  Others can either use it directly or extend over it if necessary.

To create a plugin for it:

1) Implement `HttpProxyBasePlugin` class.  Base class already provide reference to `TcpClientConnection` (`self.client`) object. See https://github.com/abhinavsingh/proxy.py/blob/84eedc46ec4f37fb10445d1ac0fef456e04eec26/proxy/http/proxy/plugin.py#L35

2) Within `before_upstream_connection` you must bail out based upon whitelist policy.  Read method doc string for `before_upstream_connection` to see available return options

3) Last thing would be from where do we load whitelist policy.  For now let's go for a file based approach

4) Currently, `proxy.py` doesn't provide a way for plugins to inject custom command line flags.  So let's use an environment variable for now

5) Let's name environment variable as `PROXY_PY_IP_WHITELIST_FILE`.  If env variable is set, then use that file to load necessary IP information

Can you also share the `yaml` file format that you are using.

Thank you

**Comment by abhinavsingh** [comment]
@guysoft Checking back if above strategy helped you write a IP whitelist plugin?  Thank you!!!

**Comment by guysoft** [comment]
Hey, sorry for filling in, I really don't know your codebase as much as you.

1. I understand it should be something along the lines of:

```python
class HttpProxyBasePluginWhitelist(ABC):
    """Base HttpProxyPlugin Plugin class.
    Implement various lifecycle event methods to customize behavior."""

    def __init__(
            self,
            uid: UUID,
            flags: Flags,
            client: TcpClientConnection,
            event_queue: EventQueue) -> None:
        self.uid = uid                  # pragma: no cover
        self.flags = flags              # pragma: no cover
        self.client = client            # pragma: no cover
        self.event_queue = event_queue  # pragma: no cover

    @abstractmethod
    def before_upstream_connection(
            self, request: HttpParser) -> Optional[HttpParser]:
        """Handler called just before Proxy upstream connection is established.
        Return optionally modified request object.
        If None is returned, upstream connection won't be established.
        Raise HttpRequestRejected or HttpProtocolException directly to drop the connection."""
        if "PROXY_PY_IP_WHITELIST_FILE":
            if not os.path.isfile(os.environ["PROXY_PY_IP_WHITELIST_FILE"]):
                raise Exception("Error whitelist path does not exist: " + str(os.environ["PROXY_PY_IP_WHITELIST_FILE"]))
            with open(os.environ["PROXY_PY_IP_WHITELIST_FILE"]) as f:
                whitelist = yaml.load(f, Loader=yaml.FullLoader)
                if self.client.addr[0] not in whitelist:
                    return
        return request  # pragma: no cover
```
I am not sure what I am changing here.
The yaml format is simple as hell, it could have been really just parsing with newline:
```
cat ../ip-request/src/ip_list.yml 
- 192.168.1.1
- 63.43.23.97
```

etc.
Lets say I set ```PROXY_PY_IP_WHITELIST_FILE=/path/to/whitlist.yal```

Now that I have this, where do I place it? How does it become a plugin?

**Comment by abhinavsingh** [comment]
@guysoft No worries.  It's easy to write a plugin.  I'll also add a doc section specifically about how to write a plugin from scratch.

Above code will not work, because you seem to have modified base HttpProxyPlugin class itself.  You must implement it's interface instead.  Take a look at [filter_by_upstream](https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/filter_by_upstream.py) plugin which is very similar to IP whitelist plugin.  Instead of filtering by IP, it filters by upstream domain names.

Let me know.

**Comment by abhinavsingh** [comment]
@guysoft For "how it becomes a plugin", please refer to [Plugin Examples](https://github.com/abhinavsingh/proxy.py#plugin-examples) section which shows how to enable a plugin.  You can put your plugin anywhere, doesn't have to be within `proxy.py` source folder.  If you are having trouble loading external plugins, check this section https://github.com/abhinavsingh/proxy.py#unable-to-load-plugins

**Comment by guysoft** [comment]
Thanks for the example, sorry I could not built it up, I am swamped here.
