### ISSUE TITLE
[Question] How to use plugins?

### ISSUE THREAD

**Issue by ololoe** [abhinavsingh/proxy.py#352]
If I wrote a plugin, how can I use it?

**Comment by ololoe** [comment]
Where to put it?

**Comment by abhinavsingh** [comment]
Please try these instructions
https://github.com/abhinavsingh/proxy.py/blob/develop/README.md#unable-to-load-plugins

Let me know if you run into any issues

Thank you

**Comment by abhinavsingh** [comment]
I hope you are able to write plugins now.  If not, please re-open this issue and happy to help further.  Thank you!!!
