### ISSUE TITLE
[Question] Unable to start from code from instructions

### ISSUE THREAD

**Issue by whitespots** [abhinavsingh/proxy.py#353]
I'm trying to follow the instructions, but each time I see this error:

```
ImportError: attempted relative import with no known parent package
```

What should I place in my environments?
PS. My target is to write a plugin for security testing, but I was able to use your project as library only.

**Comment by whitespots** [comment]
UPD. I can only launch it as a module.
But also met some problems in request editing.
I want to add any header. For this purpose, I use the ModifyPostDataPlugin.
But actually, it is not working..

```
class ModifyPostDataPlugin(HttpProxyBasePlugin):
    """Modify POST request body before sending to upstream server."""

    MODIFIED_BODY = b'{"key": "modified"}'

    def before_upstream_connection(
            self, request: HttpParser) -> Optional[HttpParser]:
        return request

    def handle_client_request(
            self, request: HttpParser) -> Optional[HttpParser]:
        request.add_header(b'TEEEEEEST', b'application/json')
        return request

    def handle_upstream_chunk(self, chunk: memoryview) -> memoryview:
        return chunk

    def on_upstream_connection_close(self) -> None:
        pass

```

**Comment by abhinavsingh** [comment]
Hi,

Does the example from the README.md
<https://github.com/abhinavsingh/proxy.py#modifypostdataplugin> works?  If
example works, then is your request being served over https?  If it's
https, then you must also enable TLS interception to modify request headers.

Let me know

Cheers
------------------------------------------------------
Abhinav Singh,
https://abhinavsingh.com
------------------------------------------------------

**Comment by abhinavsingh** [comment]
I hope problem is resolved now.  If not, please re-open this issue.  Thank you!!!

**Comment by seguri** [comment]
@abhinavsingh Is it possible to run this without installing?
```
$ git clone https://github.com/abhinavsingh/proxy.py
$ cd proxy.py/proxy
$ python3 proxy.py --port 1080
Traceback (most recent call last):
  File "/Users/mark/Documents/proxy.py/proxy/proxy.py", line 29, in <module>
    from .common.utils import bytes_, text_
ImportError: attempted relative import with no known parent package
```
