### ISSUE TITLE
Why is PROXY_TUNNEL_ESTABLISHED_RESPONSE_PKT necessary?

### ISSUE THREAD

**Issue by 1again** [abhinavsingh/proxy.py#37]
great code and praise you!

i have some question.

see the code,
proxy.py:495
```
            if self.request.method == b'CONNECT':
                self.client.queue(PROXY_TUNNEL_ESTABLISHED_RESPONSE_PKT)
            # for usual http requests, re-build request packet
            # and queue for the server with appropriate headers
            else:
                self.server.queue(self.request.build(
                    del_headers=[b'proxy-authorization', b'proxy-connection', b'connection', b'keep-alive'],
                    add_headers=[(b'Via', b'1.1 proxy.py v%s' % version), (b'Connection', b'Close')]
                ))
```

when request is https, it send CONNECT to Proxy Server.
`here is problem, why we(the proxy) tell client success?`
`why not let the remote server tell to client result?`

we should just do transpond, so i modify the code:
`self.client.queue(PROXY_TUNNEL_ESTABLISHED_RESPONSE_PKT)`
to
`self.server.queue(data)`
it's work right!

what about you think?
look forward to your reply!

**Comment by abhinavsingh** [comment]
Per specification, a proxy must return `200 OK` if the connection was successfully established. Also, clients shouldn't send further data until `200 OK` is received.

I don't think `self.server.queue(data)` will make it work. Did you give it a try?

**Comment by 1again** [comment]
you are right.
it's don't work.
i try on dynamic proxy feature, it's different.
maybe i should see the code again!
close and thanks!
