### ISSUE TITLE
Setting Public IP

### ISSUE THREAD

**Issue by Pezhvak** [abhinavsingh/proxy.py#38]
how can i set my public ip? my server has thousands of ipv6. is it possible to choose one for each proxy?

**Comment by abhinavsingh** [comment]
Duplicate of https://github.com/abhinavsingh/proxy.py/issues/36

**Comment by Pezhvak** [comment]
sorry buy public ip i mean the outgoing ip, i have ipv4 which i want to listen on and use one of my ipv6s for outgoing traffic
