### ISSUE TITLE
new pypi release?

### ISSUE THREAD

**Issue by FelixSchwarz** [abhinavsingh/proxy.py#39]
I tried to install the code from pypi as written in README. Everything seemed to work fine but I got spurious connection problems in certain situations and I wasted about one hour with debugging. Eventually I tried to git version and everything worked just fine.

Is there anything blocking a new pypi release? It seems the current git code contains important fixes when using the proxy with modern browsers.

**Comment by abhinavsingh** [comment]
You are correct. I was waiting to get major fixes in, most of them are now, but haven't pushed a new release yet. Will do so over the weekend. Thanks.

**Comment by abhinavsingh** [comment]
Done, please verify using:

`pip install --upgrade proxy.py`

Thanks.
