### ISSUE TITLE
Can I use Proxy.py to redirect my connection to a corporate proxy?

### ISSUE THREAD

**Issue by Oblivion94** [abhinavsingh/proxy.py#411]
My university uses a corporate proxy of type http (squid) with digest authentication. So it is very difficult for me to get internet access because Digest is supported by very few applications. So
I have some questions that I would like to clarify to know if I can use Proxy.py, I list them below:
1. Can it be used to give access to all applications on the system? I work on Linux.
2. If the above is true then does it support Digest authentication?
3. If both are true, do you connect without resorting to administrative privileges?

Please excuse my ignorance and thank you very much in advance. :)

**Comment by abhinavsingh** [comment]
Please find my reply inline below.


On Sun, Aug 2, 2020, 9:24 AM Oblivion94 <notifications@github.com> wrote:

> My university uses a corporate proxy of type http (squid) with digest
> authentication. So it is very difficult for me to get internet access
> because Digest is supported by very few applications. So
> I have some questions that I would like to clarify to know if I can use
> Proxy.py, I list them below:
>
>    1. Can it be used to give access to all applications on the system? I
>    work on Linux.
>
> Yes, you can setup your system to use proxy.py for all outgoing http/https
requests.  This will work for browsers + native apps.


>    1. If the above is true then does it support Digest authentication?
>
>
IIUC, digest auth is similar to http basic authentication.  For this to
work, we'll need to inject necessary digest authentication headers in
outgoing requests.

This can be achieved in proxy.py using a custom plugin, which will inject
necessary headers + use configured upstream (squid) proxy for access to the
internet.

Flow would look like this:

client <--> proxy.py with custom plugin <--> university squid <--> internet

proxy.py internally does support http basic authentication.  So you can
also use those existing facilities to construct digest authentication
headers.

Do take a look into proxy pool plugin.  Your use case is identical to what
that plugin does.

Copy that plugin, update upstream proxies in your plugin file with your
University proxy, add necessary headers into outgoing requests, start
proxy.py with your custom plugin, and things should work out e2e.


>    1. If both are true, do you connect without resorting to
>    administrative privileges?
>
> No.  For your use case, connecting with squid will require necessary
digest headers, without which proxy.py connection attempts will likely fail.


>
> Please excuse my ignorance and thank you very much in advance. :)
>

No worries, lemme know how this goes.

**Comment by abhinavsingh** [comment]
@Oblivion94 Closing this, please feel free to reopen if needed.  Also let us know if it worked out for you.  Thank you!!!
