### ISSUE TITLE
How to pass real client IP to browser

### ISSUE THREAD

**Issue by lubomirhadziev** [abhinavsingh/proxy.py#413]
Hello when I start proxy by just "proxy" command and I attach another device to this server the outgoing IP is the ip of the server not of the client. Is there a way with this proxy only to listen network traffic and public client IP to be visible for all sites ?

**Comment by abhinavsingh** [comment]
@lubomirhadziev Upstream server will always see the IP address from where the request originate.  Generally, proxies insert a `X-Forwarded-For` header in outgoing request to indicate original client IP to the server.  `proxy.py` doesn't add this header by default, but a plugin can easily add this header for you.

**Comment by lubomirhadziev** [comment]
Thanks @abhinavsingh I'll try this.
