### ISSUE TITLE
[question] How to tell to google real ip of the user 

### ISSUE THREAD

**Issue by lubomirhadziev** [abhinavsingh/proxy.py#415]
Hello in another you tell me that I can send `X-Forwarded-To` and here to set real ip of the user but it's not working.
I'm not see this header in my requests and google still see the proxy server ip.

I'm writing custom plugin with this:

```
def handle_client_request(self, request: HttpParser) -> Optional[HttpParser]:
    address = socket.gethostbyname(socket.gethostname())
    request.add_header(b'X-Forwarded-For', bytes('%s' % address, encoding='UTF-8'))

    return request
```

**Comment by abhinavsingh** [comment]
@lubomirhadziev That doesn't seem correct to me.  You are using `socket.gethostname` which is the same host where `proxy.py` is running.  See [`filter_by_client_ip`](https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/filter_by_client_ip.py#L26) plugin to see how to obtain client IP address

Also see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded _(officially spec header)_ and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For _(non-standard header)_

Overall, HTTP headers is simply a signal to upstream server about client real IP.   But upstream server may or may not respect these headers at all.  It depends upon server implementation.  Give it a try and lemme know, thank you!!!
