### ISSUE TITLE
Reverse proxy plugin - specify targets?

### ISSUE THREAD

**Issue by jil24** [abhinavsingh/proxy.py#419]
The reverse proxy plugin appears to have a hardcoded single demonstration target; while it seems fairly simple to rewrite this, it would be great to be able to specify targets and mapping urls via commandline flags.

**Comment by abhinavsingh** [comment]
@jil24 Wondering if you have anything specific in mind.  If we decide to not hardcode the sample implementation, then we are likely going to have some sort of config file (e.g. not exactly but similar to `nginx.conf` style).  Flags alone can help too if mapping count is less.

**Comment by jil24** [comment]
A config file of mappings is basically what I had in mind. I just ended up setting up ngnix for my application.

**Comment by abhinavsingh** [comment]
Exactly.  I would also recommend using Nginx until there is a strong reason
to use proxy.py for your use case e.g. modifying data on the fly.

**Comment by abhinavsingh** [comment]
I am closing this since config map can easily be maintained within the plugin.  Also, if necessary, plugin can load this config map from disk.  Unfortunately, currently, we don't have a clean way of allowing custom flags via plugins.  See https://github.com/abhinavsingh/proxy.py/issues/301

**Comment by sberney** [comment]
Can you provide an example of how I can change the target without a local development build of proxy.py? I don't see how to load a custom user-defined plugin, and looking at the source for reverse_proxy.py, I don't see that there are any options whatsoever to modify the target programmatically. So, I don't see any way to use this feature without creating a new build of proxy.py. This is hardly a proxy.py user-facing feature, then.

**Comment by abhinavsingh** [comment]
> Can you provide an example of how I can change the target without a local development build of proxy.py? I don't see how to load a custom user-defined plugin, and looking at the source for reverse_proxy.py, I don't see that there are any options whatsoever to modify the target programmatically. So, I don't see any way to use this feature without creating a new build of proxy.py. This is hardly a proxy.py user-facing feature, then.

You should be able to load external plugins.  Check this https://github.com/abhinavsingh/proxy.py#unable-to-load-plugins. Let me know if this doesn't seem to work for you for any reason.

Every built-in plugin in `proxy.py` is merely an example which users can copy/paste/modify and custom load their plugins as necessary.  We can even `parameterize reverse_proxy.py` plugin (see other existing plugin on how to expose custom command line flags).  Example, you can parameterize entire reverse_proxy.py config (for cases where reverse proxy map is static) or even pass the reverse proxy config from a file on disk or even a cache (possibilities are endless :)).

Please let me know if available options doesn't work out for you.  Happy to chip in to enable this for you if necessary.
