### ISSUE TITLE
Add the ability to monitor connections.

### ISSUE THREAD

**Issue by zurgeg** [abhinavsingh/proxy.py#434]
**Check FAQs**
Done.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to monitor connections. For example:
```
Request from [IP address] to [server]
Response from [server]: [response here]

**Describe alternatives you've considered**
My own proxy. The reason I didn't use this is because the particular thing only likes this proxy (any other ones give connection errors)

**Additional context**
None needed.

**Comment by abhinavsingh** [comment]
Hi @zurgeg 

This capability kind-of already exists.  You can write a simple plugin to start logging request and responses.  Example check [Cache Response Plugin](https://github.com/abhinavsingh/proxy.py#cacheresponsesplugin) and modify it as per your needs.

Lemme know.
Thank you

**Comment by abhinavsingh** [comment]
@zurgeg Will close this.  Please feel free to re-open if plugin doesn't help with monitoring.  Thank you!!!
