### ISSUE TITLE
Leaked semaphore objects on Python 3.8 during shutdown

### ISSUE THREAD

**Issue by karteek** [abhinavsingh/proxy.py#437]
**Describe the bug**
Python3.8's resource tracker is complaining of leaked semaphore objects on proxy.py

**To Reproduce**
1. Run `proxy.py` using `proxy` command.
2. Stop `proxy` using `ctrl+c`
4. Python complains of leaked semaphore objects.

**Expected behavior**
There shouldn't be any leaked semaphore objects

```
(venv3) ➜  ~ uname -v
Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64
(venv3) ➜  ~ python -V
Python 3.8.5
(venv3) ➜  ~ pip list | grep proxy
proxy.py          2.2.0
(venv3) ➜  ~ proxy                
2020-09-27 12:56:34,088 - pid:26406 [I] load_plugins:534 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2020-09-27 12:56:34,089 - pid:26406 [I] listen:61 - Listening on ::1:8899
2020-09-27 12:56:34,116 - pid:26406 [I] start_workers:84 - Started 8 workers
^C2020-09-27 12:56:36,583 - pid:26406 [I] shutdown:101 - Shutting down 8 workers
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 48 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by abhinavsingh** [comment]
Thank you @karteek for raising this.  I have earlier noticed similar warnings with `Python 3.8+`.  However, this only happens during **shutdown**.  On a long running `proxy.py` server, RAM usage is pretty stable, even after running for days and months.

Let's keep this issue as a tracker.  Hopefully, we can fix this going forward.

**Comment by abhinavsingh** [comment]
@karteek Took a close look.  I think these warning are harmless and no memory leak is present during runtime.

Closing this issue for now.  Let's re-open if these warnings are causing a blocker for using `proxy.py`

Thank you
