### ISSUE TITLE
Chain of proxies

### ISSUE THREAD

**Issue by songdongsheng** [abhinavsingh/proxy.py#46]
I want to setup a proxy server, it access resource regard http_proxy, https_proxy, no_proxy settings, is it possible ?

**Comment by abhinavsingh** [comment]
Apologies but its unclear to me what your objective is.  Can you expand with a couple of examples may be?  Thanks

**Comment by songdongsheng** [comment]
e.g., user A use proxy on server B, but server B also need use proxy to access some site.

**Comment by abhinavsingh** [comment]
That should work out of box.  Have you already tried setting it up?

**Comment by fy0** [comment]
Excuse me, did it supported now? @abhinavsingh

**Comment by abhinavsingh** [comment]
@fy0 Yes.  Give proxy pool plugin a try https://github.com/abhinavsingh/proxy.py#proxypoolplugin Lemme know if this doesn't suffice.

**Comment by fy0** [comment]
It works, good job!
