### ISSUE TITLE
eta on develop -> master release to pypi?

### ISSUE THREAD

**Issue by mattp-** [abhinavsingh/proxy.py#468]
hi, fantastic module! was just wondering on what timeframe you were looking to get the current refactoring in develop into a release? not to rush at all, just for planning in some internal projects here that are relying on your very recent work :) thank you!

**Comment by mattp-** [comment]
also, apologies for the not quite appropriate use of an issue for this, I couldn't see a mailing list / irc to poke.

**Comment by abhinavsingh** [comment]
Hi @mattp-

I can put one out over this weekend.  Thanks for the nudge 👍

**Comment by abhinavsingh** [comment]
Its out now!!!

`pip install proxy.py==2.3.0`

**Comment by mattp-** [comment]
Great! Thank you👍
