### ISSUE TITLE
Identifying HTTPS resource paths

### ISSUE THREAD

**Issue by JaiminRoot** [abhinavsingh/proxy.py#47]
when I run your proxy.py program when I only sniff HTTP URL not https. what's the problem

**Comment by abhinavsingh** [comment]
Can you expand or share some screenshots of what you are experiencing?

**Comment by JaiminRoot** [comment]
When i refresh the HTTPS url that time site can't open but HTTP site is
open properly

Problem see in below Video

https://drive.google.com/file/d/1852F2yR6RRUIbwzv7wnnTQgyCSOeuavQ/view?usp=drivesdk

Thanks

**Comment by abhinavsingh** [comment]
Thanks for the response, pretty unusual I would say.

1. I see you are using develop branch, but that should be OK.
2. I tried running `proxy.py` from `develop` branch locally (on MacOSX) and curl for HTTPS works well `curl -v -x localhost:8899 https://httpbin.org/get`.  I also gave it a spin via browser by changing system proxy and things look good to me.

Can you try the curl command and see where it gets?

I am suspecting it is either related to:
a) Your proxy settings.  Can you share some detail on how and where do you enable proxy.py as a proxy server?
b) Something specific on your Linux distribution which is blocking https traffic route to the proxy server (firewall, iptable rules)

**Comment by JaiminRoot** [comment]
When i run your program
I get some problem not error

I get HTTP domain not full url but i get HTTP full url using your code.
Should i sniff HTTPS full url using your code

I use Ubuntu OS

Please see in video
https://drive.google.com/file/d/1nZOeR4yf7rD1XSRUaQ8ttolckjhUznxn/view?usp=drivesdk

**Comment by abhinavsingh** [comment]
Ok, so from your latest video I understand HTTP and HTTPS both actually work fine.  That's good to know.

For HTTPS, we only know the upstream server address where the CONNECT request was made.  Unfortunately, we cannot know resources accessed over the established tunnel.

**Comment by JaiminRoot** [comment]
Thnaks for your response

Btw is it possible to sniff HTTPS full path url using proxy or other way

Like - https://anetly.in/internal/login.html

**Comment by abhinavsingh** [comment]
You need a proxy capable of man-in-the-middle attacks.  I'll close this thread for now.
