### ISSUE TITLE
Basic authentication is broken

### ISSUE THREAD

**Issue by howardmoore** [abhinavsingh/proxy.py#481]
Basic authentication succeeds if any credentials are supplied, not just the correct ones. The reason is that the if statement that validates the credentials uses 'and' when it should use 'or'.
https://github.com/abhinavsingh/proxy.py/blob/0f78e74705e295bbfccfba342bf9fd34a9aa9103/proxy/http/proxy/auth.py#L36-L40

**Comment by abhinavsingh** [comment]
Thanks @howardmoore for pointing this out.  I have made the necessary fix.  Unfortunately, looks like tests never checked for this logic and hence this went by in some refactoring.  I'll be making an official release shortly.
