### ISSUE TITLE
Intermittent error: OSError when flushing buffer to client: The operation did not complete (write) (_ssl.c:2423)

### ISSUE THREAD

**Issue by nilayp** [abhinavsingh/proxy.py#507]
**Describe the bug**
I've started proxy.py with no plugins installed. Then, I started a process which make GET requests through the proxy of objects that are ~4MB in size.  Intermittently, some of the requests receive the following error:

```
OSError when flushing buffer to client.
```

I changed [proxy/http/handler.py, line 245](https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/handler.py#L245) to `logger.error('OSError when flushing buffer to client: {0}'.format(err))` to emit a slightly more detailed error message.

```
OSError when flushing buffer to client: The operation did not complete (write) (_ssl.c:2423)
```

**To Reproduce**
1. Run `proxy.py` as `python -m proxy --ca-key-file ca-key.pem --ca-cert-file ca-cert.pem --ca-signing-key-file ca-signing-key.pem --hostname 0.0.0.0`
2. Run a script which fetches multiple objects
3. See error after a few minutes of successfully proxied objects.

**Expected behavior**
No errors.

**Version information**
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Python: 3.7.8
 - proxy.py Version: 2.3.0

**Additional context**
I noticed a [very similar issue](https://github.com/abhinavsingh/proxy.py/issues/498) reported recently. However, when I reproduced that problem and emitted the full error message, it was different:

```
OSError when flushing buffer to client: EOF occurred in violation of protocol (_ssl.c:2423)
```

Therefore, I opened a new issue.

**Screenshots**

**Comment by nilayp** [comment]
A few discoveries since I created this bug.

I thought I'd try this on Linux to see if perhaps my problem was macOS related. I spun up an Ubuntu 20.04.02 LTS host with Python 3.8.7. When I ran my script, I still received an exception, but it was from a different part of the stack. See the output below.

That said - I think I discovered the true reason this error is occurring. My script that generates HTTP requests causes two different hosts to use the proxy simultaneously. When I only use one host, the problem completely goes away. It appears to be a race condition caused by the concurrency of two hosts communicating to the proxy simulatenously?

```
2021-02-26 23:26:51,113 - pid:78902 [E] intercept:539 - OSError when wrapping client
Traceback (most recent call last):
  File "/home/nilayp/proxy2.py/proxy/http/proxy/server.py", line 529, in intercept
    self.wrap_client()
  File "/home/nilayp/proxy2.py/proxy/http/proxy/server.py", line 559, in wrap_client
    self.client.wrap(self.flags.ca_signing_key_file, generated_cert)
  File "/home/nilayp/proxy2.py/proxy/core/connection/client.py", line 37, in wrap
    self._conn = ssl.wrap_socket(
  File "/home/nilayp/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "/home/nilayp/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/nilayp/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/nilayp/.pyenv/versions/3.8.7/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
```

**Comment by abhinavsingh** [comment]
@nilayp Hi Nilay, thanks for reporting this.  A few thoughts:

1. `OSError when flushing buffer to client: The operation did not complete (write)` can happen due to few reasons:
   - Client prematurely closed connection
   - Queued packets are larger than configured max packet size for the connection with client
2. `ssl.SSLEOFError: EOF occurred in violation of protocol` is again an indication that negotiation didn't go well with clients.  This can happen again for numerous reasons.

Regarding race condition, we do generate certificates within a lock.  But
a) we don't have any tests which asserts for smooth operations during such race condition
b) Also use of
```
        # Used to synchronization during certificate generation.
        lock = threading.Lock()
```

might not be right considering `proxy.py` handlers can run across different processes, where `threading.Lock` will not suffice, instead `multiprocessing.Lock` will be a good choice.

Can you try, ` lock = multiprocessing.Lock()` and see if that helps?

**Comment by nilayp** [comment]
Thank you for the quick response. I can't tell you why, but the problem is now 100% NOT reproducible. I used to be able to reproduce this within seconds of running my client script, but now I can't get it to reproduce with either the `lock = threading.lock()` or the `lock = multiprocessing.lock()` instructions. I have no idea what could have changed, but something did. I'll update the ticket if I can figure it out, until then... I'm good to go. 

I'll also add that you need to teach a MasterClass in authoring open source project README files. Your instructions are excellent: simple, clear and detailed. I wish every open source project in github documented their repos as well as you have. Great work and once again, thank you!
