### ISSUE TITLE
proxy server some web can't open

### ISSUE THREAD

**Issue by robinxie84** [abhinavsingh/proxy.py#511]
`cmd:proxy --port 5900 --hostname 0.0.0.0 --timeout 120  --log-level d`

but server report error info
`read_from_descriptors:200 - Connection reset by upstream: ConnectionResetError(104, 'Connection reset by peer')`

web site can't open by proxy

**Comment by abhinavsingh** [comment]
@robinxie84 As indicated by the logs, connection was closed by upstream server and hence `proxy.py` is unable to complete the request.

**Comment by abhinavsingh** [comment]
Closing this now, please re-open if any problem arises.  Thank you!!!
