### ISSUE TITLE
Using .p12 (PKCS 12) with proxy SSL interception on Windows

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#528]
I am running `proxy.py` on Windows and basically trying to intercept traffic on terminal and analyze what is going through the network. I am so able to do this with HTTP. However, for HTTPS, i need to generate CA certificates. On windows, i followed the procedure for cert gen and i came to know that window generates a single `p12` file to certificate which contains both private and public keys. 

Now, how can i use this p12 file with proxy.py? 
Because according the documentation, i have to provide the `.pem` and `.key` file like this: 
```
proxy \
    --plugins proxy.plugin.CacheResponsesPlugin \
    --ca-key-file ca-key.pem \
    --ca-cert-file ca-cert.pem \
    --ca-signing-key-file ca-signing-key.pem
```

**Comment by abhinavsingh** [comment]
@hash3liZer You can split them as necessary.  Example:

```
openssl pkcs12 -in path.p12 -out newfile.crt.pem -clcerts -nokeys
openssl pkcs12 -in path.p12 -out newfile.key.pem -nocerts -nodes
```

See https://stackoverflow.com/a/15144560/414221
