### ISSUE TITLE
CLI arguments only accepts uppercase log level

### ISSUE THREAD

**Issue by lukemin** [abhinavsingh/proxy.py#53]
```
[root@instance-2 google]# proxy.py --port 8483 --basic-auth user:pws --log-level error
Traceback (most recent call last):
  File "/bin/proxy.py", line 731, in <module>
    main()
  File "/bin/proxy.py", line 710, in main
    format='%(asctime)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s')
  File "/usr/lib64/python2.7/logging/__init__.py", line 1540, in basicConfig
    root.setLevel(level)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1125, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib64/python2.7/logging/__init__.py", line 190, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)
TypeError: Level not an integer or a valid string: <function error at 0x7f93e6360500>
```

**Comment by abhinavsingh** [comment]
Marked this issue as feature enhancement as I think `proxy.py` can do much better here.  Feel free to send a PR if you want :) 

For now please use uppercase e.g.

`proxy.py --log-level ERROR`

**Comment by lukemin** [comment]
the window became freezed after I typed proxy.py --log-level ERROR
![1562917368(1)](https://user-images.githubusercontent.com/12003375/61111349-f7846780-a4bb-11e9-83d5-e932ac58c23c.png)

**Comment by lukemin** [comment]
First Warning Massage when installed proxy.py
[root@instance-2 google]# pip install --upgrade proxy.py
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.doubanio.com/simple
From cffi callback <function _verify_callback at 0x7f61a4c50410>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Requirement already up-to-date: proxy.py in /usr/lib/python2.7/site-packages (0.3)

**Comment by abhinavsingh** [comment]
@lukemin Can you provide more information about your host? OS, Python version etc.  I would like to replicate and see what is going wrong here. I have never experienced such a thing before. Thanks

**Comment by lukemin** [comment]
[root@instance-2 google]# python -V
Python 2.7.5
[root@instance-2 google]# python3 -V
Python 3.7.4
[root@instance-2 google]# cat  /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
[root@instance-2 google]# cat /proc/version
Linux version 5.2.0-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Mon Jul 8 09:37:45 EDT 2019
[root@instance-2 google]#  uname -a
Linux instance-2 5.2.0-1.el7.elrepo.x86_64 #1 SMP Mon Jul 8 09:37:45 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abhinavsingh** [comment]
Hi @lukemin ,

Don't think `proxy.py` is hanging, I see you have set the log level to error which simply doesn't print anything, as there are no errors happening.

Did you try connecting to the proxy server on port 8899?

**Comment by lukemin** [comment]
yes， I  tried connecting to the port 8899 in setting of IE, but I couldnot access sites blocked by firewall.




------------------ 原始邮件 ------------------
发件人: "Abhinav Singh"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 中午11:43
收件人: "abhinavsingh/proxy.py"<proxy.py@noreply.github.com>; 
抄送: "Lu Kemin"<lukemin@vip.qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [abhinavsingh/proxy.py] CLI arguments only accepts uppercase loglevel (#53)




Hi @lukemin ,
 
Don't think proxy.py is hanging, I see you have set the log level to error which simply doesn't print anything, as there are no errors happening.
 
Did you try connecting to the proxy server on port 8899?
 
&mdash;

**Comment by abhinavsingh** [comment]
Please unblock access to sites via Firewall, `proxy.py` is not meant to bypass firewalls.  Thank you.

**Comment by lukemin** [comment]
please reopen this issue. there are some misunderstandings between us. The Firewall what I metioned is Firewall of Government, not the firewall of my pc. and I wanna use this script to set up a proxy to bypass the FOG to access some blocked webpages.Waht I have done is :
1.set up a proxy with your script on my vps
2.set the parameters of the proxy to my web browser-IE
3.try to access the blocked sites
Step3 was failed because the connection between my pc and my vps is http, not https.
How can I set up https connection between my pc and vps when I pointed a domained to my vps and got a certificatesof the domain from **let's encryption**

**Comment by abhinavsingh** [comment]
@lukemin Lets continue using https://github.com/abhinavsingh/proxy.py/issues/61 for tracking firewall bypass use-case, since this issue was repurposed for logging level fixes.
