### ISSUE TITLE
Fix PoolProxyPlugin

### ISSUE THREAD

**Issue by dmitryTsatsarin** [abhinavsingh/proxy.py#537]
Let me be nasty customer. Who does want to fix PoolProxyPlugin? Ready to pay 100$.

**Comment by abhinavsingh** [comment]
Thanks @dmitryTsatsarin for creating this bounty.  Probably you must also list items to be addressed in ProxyPoolPlugin.  Hopefully it will attract more response.  I'll also post this on the gitter chat.  Can also create necessary tracker issues to address these item in future releases.  Thank you!!!

**Comment by edorofeev** [comment]
I've tested it to, and got errors too.
On client:
```curl https://httpbin.org/headers -x localhost:8899 -k -v
*   Trying ::1:8899...
* Connected to localhost (::1) port 8899 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to httpbin.org:443
> CONNECT httpbin.org:443 HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.74.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=utf-8
< Server: ProxyChain
< Connection: close
< Content-Length: 53
< 
* Received HTTP code 400 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 400 from proxy after CONNECT
```
On server:
```ConnectionResetError(54, 'Connection reset by peer')```

Where I can find an example how to use upstream proxy without rotation?

**Comment by abhinavsingh** [comment]
@edorofeev `ProxyPoolPlugin` is just an example for `proxy.py` users.  If necessary, please copy/paste this plugin into your own custom plugin https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/proxy_pool.py

Modify your custom plugin (now based on `ProxyPoolPlugin`) as necessary.  Example, you can have a single upstream proxy instance within `UPSTREAM_PROXY_POOL` variable (https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/proxy_pool.py#L27) OR simply deprecate the use of `UPSTREAM_PROXY_POOL` and pass your upstream proxy server using command line flags OR just hardcode upstream proxy within your custom plugin code.

Having said that, there are certain architectural issues currently, which prohibit `ProxyPoolPlugin` or it's extensions from performing true asynchronous operations.  Problem arises from the fact that, `proxy.py` is completely asynchronous, but it currently doesn't exposes `event_loop` to its plugins.  Hence, if and when plugins are need of asynchronous network IO operations, plugin developers need a hack.  By exposing internal `event_loop`, plugins can simply tie with existing asynchronous IO system.

In the meantime, you can modify `ProxyPoolPlugin` as necessary to get past above mentioned limitations.

**Comment by abhinavsingh** [comment]
My dear nasty customers :), good news is that support for allowing plugins to register custom descriptors has landed.  See https://github.com/abhinavsingh/proxy.py/pull/638  This will allow several issues with the proxy pool plugin to be addressed.

One major issue currently we face is that, proxy pool plugin performs synchronous socket operations.  This didn't use to fit well with async proxy.py core.  PR #638 will now allow plugins to register read/write descriptors, so now everything can be kept async and performant :)

PS: Plugin should be updated to take effect.  I'll give it a try sometime in the coming week.

**Comment by abhinavsingh** [comment]
Check this out https://github.com/abhinavsingh/proxy.py/pull/645 should work reliably for both http and https requests.  I think web socket requests might not be kept alive for long, but that is something we can easily address going forward.  Currently, I am using proxy pool setup locally (code from linked PR) and able to execute all my browsing needs without any visible issues :)
