### ISSUE TITLE
Upgrade to 'Elite Proxy / Highly Anonymous Proxy' per proxy-checker results

### ISSUE THREAD

**Issue by jackjieYYY** [abhinavsingh/proxy.py#560]
Dear developer, 

the result of the proxy checker is " Anonymous Proxy " when I use " python3 -m proxy --enable-dashboard --hostname 0.0.0.0 --port 9000 " to start my proxy.  Is there any way to update the level to " Elite Proxy / Highly Anonymous Proxy "

thanks! 

![image](https://user-images.githubusercontent.com/53422254/120478728-7fe1bd80-c3f0-11eb-873e-30c2d1a0d03b.png)
![image](https://user-images.githubusercontent.com/53422254/120478819-98ea6e80-c3f0-11eb-9047-762beb8bc1b2.png)

proxy checker: http://www.proxy-checker.org/result.php

**Comment by abhinavsingh** [comment]
@jackjieYYY Thank you for requesting this.  I have marked it as enhancement instead of bug.  Point is current I don't even clearly understand what it requires to pass the highly anonymous proxy levels.  But I am interested in it and will look into to support this feature in future.

**Comment by jackjieYYY** [comment]
> @jackjieYYY Thank you for requesting this. I have marked it as enhancement instead of bug. Point is current I don't even clearly understand what it requires to pass the highly anonymous proxy levels. But I am interested in it and will look into to support this feature in future.

thanks for your reply~~ Looking forward to your good news, best wishes!!!

**Comment by jackjieYYY** [comment]
> @jackjieYYY Thank you for requesting this. I have marked it as enhancement instead of bug. Point is current I don't even clearly understand what it requires to pass the highly anonymous proxy levels. But I am interested in it and will look into to support this feature in future.

Dear developer, today I build an HTTP service using FastAPI and try to find the header difference wheater using the proxy.

Here are the screenshots:

![image](https://user-images.githubusercontent.com/53422254/120662195-47171680-c4cc-11eb-8382-b4e5ff8eb3b0.png)
![image](https://user-images.githubusercontent.com/53422254/120662533-952c1a00-c4cc-11eb-91bb-3d2dc17e5af9.png)
![image](https://user-images.githubusercontent.com/53422254/120662742-b8ef6000-c4cc-11eb-979c-30ece5b1c947.png)

Obviously, the header['via'] field reveals that we are using a proxy but does not tell the web server our real IP.

and these is related Codes:

![image](https://user-images.githubusercontent.com/53422254/120663213-2dc29a00-c4cd-11eb-8735-2b6cb8f7d0cc.png)

Thank you for reading and look forward to your updates!

**Comment by abhinavsingh** [comment]
@jackjieYYY I see, yep `Via` header would reveal it.

On line 369, there is a provision to delete headers before sending to upstream.  You can use `--disable-headers` flag, see https://github.com/abhinavsingh/proxy.py#flags to remove `Via` header.

Please let me know if this doesn't help.

**Comment by jackjieYYY** [comment]
wellllllllllll, it doesn't work...

**Comment by abhinavsingh** [comment]
@jackjieYYY I double checked today and `proxy --disable-headers via` seems to work fine.  This avoids sending the `Via` header.  Please let me know what exactly did you try, so that I can cross verify the same

**Comment by abhinavsingh** [comment]
Closing this now as `proxy --disable-headers via` seems to achieve the desired result.  If this is still not working correctly for you, please feel free to re-open this issue.  Thank you.
