### ISSUE TITLE
[Docker] Container not in-sync with PIP released package

### ISSUE THREAD

**Issue by alexsanderp** [abhinavsingh/proxy.py#566]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a bug report.

**Describe the bug**
Proxy prints a  warning message `ConnectionResetError(104, 'Connection reset by peer')` in version 2.3.1 (PIP version):

```
2021-06-12 10:24:44,993 - pid:19911 [I] load_plugins:334 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2021-06-12 10:24:44,993 - pid:19911 [I] listen:113 - Listening on 0.0.0.0:8899
2021-06-12 10:24:45,002 - pid:19911 [I] start_workers:136 - Started 8 workers
2021-06-12 10:24:47,296 - pid:19918 [W] handle_readables:261 - ConnectionResetError(104, 'Connection reset by peer')
2021-06-12 10:24:47,296 - pid:19918 [I] access_log:389 - 127.0.0.1:37092 - CONNECT ipinfo.io:443 - 5574 bytes - 211.99 ms
^C2021-06-12 10:24:50,724 - pid:19911 [I] shutdown:153 - Shutting down 8 workers
```

Using dockerhub version 2.3.1 the message is also not printed.

**To Reproduce**
1. Install proxy.py using pip `pip3 install proxy.py"
2. Create a test.py file:
```
import proxy

proxy.main([
    '--hostname', '0.0.0.0'
])
``` 
3. Run `python3 test.py`
4. Run `curl https://ipinfo.io/ip --proxy http://localhost:8899`

**Expected behavior**
The message is just a warning and the application works normally. I'm opening the issue to report the difference between PIP and Dockerhub version. I don't know if this message can cause any problems.

**Version information**
 - OS: [e.g. Linux Mint 20.1 Cinnamon]
 - Browser [curl]
 - Device: [e.g. Notebook]
 - proxy.py Version [e.g. 2.3.1]

**Comment by abhinavsingh** [comment]
@alexsanderp I don't think it's a bug.  As the error states, "connection was reset by peer", so nothing that a proxy could do here.  Is the connection working as expected without proxy?

**Comment by abhinavsingh** [comment]
@alexsanderp Thanks for pointing out Docker and PIP discrepancy, I'll address it in coming week.

**Comment by abhinavsingh** [comment]
Created PR in preparation of next release.  Ref

- https://github.com/abhinavsingh/proxy.py/pull/777

See PR description for release plan.

**Comment by abhinavsingh** [comment]
Closing this now.

`develop` branch containers are now available via GHCR latest tag
`stable` release containers are available via DockerHub latest tag

Intermediate, `rc`, `alpha`, `beta`, `PR` releases are available on both GHCR, DockerHub via individual tags.

Refer to https://github.com/abhinavsingh/proxy.py#using-docker for more details.
