### ISSUE TITLE
Getting orignal request of an upstream response during Interception

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#579]
Talking about TLS Interception, let's just say i am basically reading the incoming requests and responses respectively. And for that we use plugins for capturing whatever passing through the proxy. Now, i want to deduce some results based on specific response & request combined. However, when i receive a response, i don't have access to its request. Let's talk about `handle_upstream_chunk` while creating a custom proxy plugin: 

```python
def handle_upstream_chunk(self, chunk: memoryview) -> memoryview:
        """Handler called right after receiving raw response from upstream server.
        For HTTPS connections, chunk will be encrypted unless
        TLS interception is also enabled."""
        return chunk  # pragma: no cove
```

In above function, we do have a chunk which is a memoryview and we can get the complete response using `chunk.tobytes()`. But there's not way to access the request to this chunk. Or maybe there is and i am lacking knowledge in this specific area. 

So, i hope you do understand what ia m trying to say. Currently,  I have not figured out any alternative. However, i think its better to maybe pass a request argument alongside the chunk argument or the `HttpProxyBasePlugin` should have 2 attributes `request` and `response` respectively. I've seen one example with `ModifyChunkResponsePlugin` where you have implemented a response attribute for the plugin class. However, i am not sure if that would hold the value while passing the response.

**Comment by abhinavsingh** [comment]
Request parameter passed during `before_upstream_connection` can be cached and re-used https://github.com/abhinavsingh/proxy.py/blob/2041809f881d0101e43f098304130cc3cf926e28/proxy/http/proxy/plugin.py#L46

`proxy.py` creates a new instance of plugin class per request.  So, you could simply do, `self.request = request` during `before_upstream_connection` and later access it.  

Can you try and lemme know if this helps?

**Comment by hash3liZer** [comment]
Checked a while ago. I guess separate instance for each request makes sense. I assumed that a single instance was created. It worked perfectly. However, I still have a question. What would be the perfect solution to parse the chunk in `handle_upstream_chunk`?

**Comment by abhinavsingh** [comment]
There is a ChunkParser class (used internally by HttpParser).  You can make use of it.

**Comment by hash3liZer** [comment]
Perfect. Thanks. I guess we can close it now.
