### ISSUE TITLE
[ChunkParser] Chunks are being skipped during interception

### ISSUE THREAD

**Issue by hash3liZer** [abhinavsingh/proxy.py#602]
Hi, once again. So, i was developing a plugin for intercepting responses coming from upstream server. Sometimes it intercepts perfect. However, most of the time chunks are being skipped. According to plugin base, i should use this method to intercept all the chunks:

```python
def handle_upstream_chunk(chunk):
    return chunk
```

It does work. But most of the important chunks are being skipped. They are received in the browser however perfectly. But when it comes to interception, many important parts are being missed. I don't know what i am missing here. My approach is this condition: 

```python
counter = 0

def handle_upstream_chunk(chunk):
    self.response.parse(chunk)
    if b"content-type" in self.response.headers and "application/json" in self.response.header[b"content-type"][1] and self.response.body:
        counter += 1
        print("Counter at: ", counter)
    return chunk
```

Now, open two different gmail tabs with different emails sequentially. You will see the difference. Repeat this 5-6 times by clearing cookies and in private tabs etc. Many times the response is being skipped.

**Comment by abhinavsingh** [comment]
Hi @hash3liZer , I am unsure if chunks are being skipped.  If they are being skipped, website in browser itself will not work.  However, what can happen is that server is not sending a chunked response every time.

To verify if chunks are being missed, you can verify with https://github.com/abhinavsingh/proxy.py#modifychunkresponseplugin example.  Use a very high value for chunks to stream from httpbin.org.  Plugin must receive all expected chunks.

Overall, my point being, problem might be somewhere else (not necessarily with proxy.py) but it gives an impression that chunks are being missed/skipped.  While the fact is that if chunks are being skipped, website will not work properly in the browser.

Unfortunately, I am very tied up with another project.  But I do use proxy.py daily without any issues or broken websites.  Let me know about your findings.

**Comment by hash3liZer** [comment]
Hi @abhinavsingh , i've confirmed this after reading the whole code `Parser` class. The problem lies in `proxy.http.chunk_parser.py` class. The chunks are coming perfectly. However, when you parse them using the `response.parse` method, some chunks are somehow being ignored. This problem occurs only when response has header: 'Transfer-Encoding: chunked' for which `ChunkParser` class is used. 

Upon deep analysis, i also found that the first 2 or 3 chunks are parsed correctly. The chunks after that somehow are being skipped. I've not tried to proofread the code though. But the error for sure is coming from the `ChunkParser` class.

**Comment by abhinavsingh** [comment]
@hash3liZer There are tests for `ChunkParser` here https://github.com/abhinavsingh/proxy.py/blob/develop/tests/http/test_chunk_parser.py. One idea would be to input a suspected chunk response in test case and see if `ChunkParser` behaves expectedly.  We can address the issue more concretely then.  Thank you!!!

**Comment by abhinavsingh** [comment]
@hash3liZer Were you able to reproduce the bug at your end?

> Now, open two different gmail tabs with different emails sequentially. You will see the difference. Repeat this 5-6 times by clearing cookies and in private tabs etc. Many times the response is being skipped.

Can you use this scenario at your end?   Add some logging statements, specially within `connection.py` class.  This will let you verify/dump/create a reproducible scenario, by capturing what is being received from upstream (in raw form) and which of these chunks are not being received by the plugin.

<img width="640" alt="Screen Shot 2021-12-18 at 8 19 27 AM" src="https://user-images.githubusercontent.com/126065/146626525-5f5cf798-0275-4ba7-9132-f9b5dad99269.png">

May be that can be a good start to dig into it further.

**Comment by abhinavsingh** [comment]
Closing this.  Please re-open once we have more data for further investigation.  Thank you!!!
