### ISSUE TITLE
More of a question then an issue...

### ISSUE THREAD

**Issue by PoeticDeath** [abhinavsingh/proxy.py#606]
I've been trying to find where the actual HTTP/HTTPS requests are. What a mean is when I'm on the proxy server and request for example google.com, what on the proxy server goes to retrieve google.com's content after the request is received?

**Comment by abhinavsingh** [comment]
All proxy related implementation is here https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/proxy/server.py

`HttpProxyPlugin` implements `HttpProtocolHandlerPlugin` interface to tie into HTTP lifecycle.

Hope this helps.
