### ISSUE TITLE
HTTPS Proxy connection from client 

### ISSUE THREAD

**Issue by lukemin** [abhinavsingh/proxy.py#61]
HTTPS Proxy connection from client
I bind a domain to my vps, how to set up https connection between client and vps?

**Comment by abhinavsingh** [comment]
lukemin@ what error do you see?  Does the request just hangs or does it
error out with exception.

**Comment by lukemin** [comment]
Take twitter as example， in settings and privacy - proxy opinion, I wanna setup a https based proxy by your script, but It didn't work at all.

**Comment by abhinavsingh** [comment]
@lukemin Can you provide environment details. Everything seems to work just fine for me locally, I also tried on remote servers.   You said it didn't work at all, can you give us some logs?  Start as `proxy.py --log-level d` to share debug level logs.  Thank you

**Comment by lukemin** [comment]
[root@instance-2 google]# python3 proxy.py --log-level d
Traceback (most recent call last):
  File "proxy.py", line 762, in <module>
    main()
  File "proxy.py", line 739, in main
    logging.basicConfig(level=getattr(logging, args.log_level),
AttributeError: module 'logging' has no attribute 'd'
[root@instance-2 google]# python2 ^C
[root@instance-2 google]# python2 proxy.py --log-level d
Traceback (most recent call last):
  File "proxy.py", line 762, in <module>
    main()
  File "proxy.py", line 739, in main
    logging.basicConfig(level=getattr(logging, args.log_level),
AttributeError: 'module' object has no attribute 'd'

**Comment by abhinavsingh** [comment]
You clearly are not using latest from develop  branch which supports short names for log level.  Could you either [download latest](https://github.com/abhinavsingh/proxy.py/archive/develop.zip) OR simply use `--log-level DEBUG`

**Comment by abhinavsingh** [comment]
I am hoping things worked out after upgrading.  Feel free to re-open if the issue persists at your end.  Thank you.
