### ISSUE TITLE
How do I configure the reverse proxy?

### ISSUE THREAD

**Issue by Nebulizer1213** [abhinavsingh/proxy.py#621]
Is there a way to make a config file for the reverse proxy?

**Comment by abhinavsingh** [comment]
@Nebulizer1213 Unfortunately no, a config based solution doesn't exist out-of-box.  But you should be able to easily modify this plugin for your needs.  https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/reverse_proxy.py#L46-L49

Here is what I would do:

1) Copy this plugin as `my_reverse_proxy.py`
2) Add a `flag` which accepts path to config file
3) On server startup, load this config and prepare `routes`.  See `def routes(self) -> List[Tuple[int, str]]:` method in the example.

That should get you going.  Let me know how it goes.

**Comment by abhinavsingh** [comment]
@Nebulizer1213 Closing this now.  Please feel free to re-open if you are still facing issues with this.  Thank you!!!
