### ISSUE TITLE
[forward compat?] Support Python 3.10

### ISSUE THREAD

**Issue by webknjaz** [abhinavsingh/proxy.py#622]
**Describe the bug**

I've recently integrated proxy.py into the test suite of aiohttp. Now that we're trying to add Python 3.10 to the CI, the tests that interact with an instance of proxy.py get a TLS handshake timeout.

I haven't looked into it but my guess is that proxy.py may be incompatible with Python 3.10.

**To Reproduce**

1. Clone aio-libs/aiohttp
2. Run `make vvtest`

**Expected behavior**

It should work.

**Version information**
 - OS: Ubuntu with Python 3.10 activated
 - Browser: N/A
 - Device: GHA CI/CD
 - proxy.py Version 2.3.1

**Additional context**

https://github.com/aio-libs/aiohttp/pull/5927

**Screenshots**

N/A

**Comment by abhinavsingh** [comment]
Thank you @webknjaz for trying it on `Python 3.10`.  I haven't yet got my hands on `3.10`.  I'll try to jump on it in coming week and see how it goes.

**Comment by webknjaz** [comment]
Thanks, that should be helpful! I haven't had time to look into that specific error myself but if I'll be able to check it out, I'll report back here too.

**Comment by abhinavsingh** [comment]
@webknjaz Should we look back into it within `aiohttp` or do we need to get into `proxy.py` deeper.  In general, `proxy.py` seems to work fine.  I am now using it for more than a month on `Python 3.10`.  Wdyt?

**Comment by webknjaz** [comment]
Well, I'll only be able to check it in that CI once you make a release.
