### ISSUE TITLE
Custom DNS

### ISSUE THREAD

**Issue by DUOLabs333** [abhinavsingh/proxy.py#664]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a feature request.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A custom option that forces all DNS queries to go through a specified server.

**Describe alternatives you've considered**

**Additional context**

**Comment by abhinavsingh** [comment]
@DUOLabs333 Does this help https://github.com/abhinavsingh/proxy.py/pull/671

Can you give `CustomDnsResolverPlugin` a try.  Add your custom code as necessary.  Let me know if you run into any issues.

Thank you for bringing this to our attention :)

**Comment by abhinavsingh** [comment]
Note that, `proxy.py` won't allow you to directly set a DNS resolver.  Instead, plugins must perform DNS resolution within `resolve_dns` callback and return the expected response.
