### ISSUE TITLE
Auto-detect IPv4 / IPv6 listen based upon --hostname arg

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#71]
For brief background see https://github.com/abhinavsingh/proxy.py/issues/68#issuecomment-532799345

**Comment by mbatrawi** [comment]
running proxy.py  on one machine
2019-09-19 19:37:31,760 - INFO - pid:6840 - load_plugins:1151 - Loaded plugin <class 'proxy.HttpProxyPlugin'>
2019-09-19 19:37:31,760 - INFO - pid:6840 - setup:262 - Starting 4 workers
2019-09-19 19:37:31,792 - INFO - pid:6840 - run:225 - Started server on 0.0.0.0:10008
configure firefox on second machine
proxy not responding on first machine and keep 4 lines without change
019-09-19 19:37:31,760 - INFO - pid:6840 - load_plugins:1151 - Loaded plugin <class 'proxy.HttpProxyPlugin'>
2019-09-19 19:37:31,760 - INFO - pid:6840 - setup:262 - Starting 4 workers
2019-09-19 19:37:31,792 - INFO - pid:6840 - run:225 - Started server on 0.0.0.0:10008 
please advise

**Comment by abhinavsingh** [comment]
@mbatrawi As commented on separate thread, I don't think your requests even reach `proxy.py` on the other machine, kindly verify your setup.

PR #76 fixes the original concern raised in this issue.  You should be able to simply use `--hostname 0.0.0.0` without need of also passing `--ipv4` flag.

**Comment by mbatrawi** [comment]
I am using proxy master
Python 3.6 proxy.py  —port 12500  —hostname 0.0.0.0

On 22 Sep 2019, at 5:57 AM, Abhinav Singh <notifications@github.com> wrote:

﻿

@mbatrawi<https://github.com/mbatrawi> As commented on separate thread, I don't think your requests even reach proxy.py on the other machine, kindly verify your setup.

PR #76<https://github.com/abhinavsingh/proxy.py/pull/76> fixes the original concern raised in this issue. You should be able to simply use --hostname 0.0.0.0 without need of also passing --ipv4 flag.

**Comment by mbatrawi** [comment]
kata@triton ~ $ clear
kata@triton ~ $ curl -v -c 127.0.0.1:12509 http://httpbin.org/get
*   Trying 3.222.220.121...
* TCP_NODELAY set
* Connected to httpbin.org (3.222.220.121) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.57.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Sun, 22 Sep 2019 05:03:22 GMT
< Referrer-Policy: no-referrer-when-downgrade
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Content-Length: 200
< Connection: keep-alive
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.57.0"
  },
  "origin": "194.14.45.10, 194.14.45.10",
  "url": "https://httpbin.org/get"
}
* Connection #0 to host httpbin.org left intact
kata@triton ~ $


On 22 Sep 2019, at 5:57 AM, Abhinav Singh <notifications@github.com> wrote:

﻿

@mbatrawi<https://github.com/mbatrawi> As commented on separate thread, I don't think your requests even reach proxy.py on the other machine, kindly verify your setup.

PR #76<https://github.com/abhinavsingh/proxy.py/pull/76> fixes the original concern raised in this issue. You should be able to simply use --hostname 0.0.0.0 without need of also passing --ipv4 flag.

**Comment by abhinavsingh** [comment]
@mbatrawi Great, looks like it worked out for you :)  Thanks

**Comment by mbatrawi** [comment]
But I configured firefox as usual
I can’t browse
Regards

On 22 Sep 2019, at 10:34 AM, Abhinav Singh <notifications@github.com> wrote:

﻿

@mbatrawi<https://github.com/mbatrawi> Great, looks like it worked out for you :) Thanks

**Comment by abhinavsingh** [comment]
@mbatrawi That sounds more like a browser configuration issue to me.  At-least now you are able to hit `proxy.py` over the network :)
