### ISSUE TITLE
Plugins usage documentation

### ISSUE THREAD

**Issue by NikhilMJain** [abhinavsingh/proxy.py#72]

**Comment by abhinavsingh** [comment]
@NikhilMJain Thanks for highlighting this, but unsure why you closed this down.  Plugins are very much a WIP but I do think they deserve more documentation.

**Comment by NikhilMJain** [comment]
@abhinavsingh I closed it by mistake. I was going to reopen it.

Can you please add documentation for plugins?

I tried adding a plugin but I am not able to pass plugins as arguments.

**Comment by abhinavsingh** [comment]
Agreed, we deserve more documentation.

Btw, have you tried these [plugin examples](https://github.com/abhinavsingh/proxy.py/blob/develop/plugin_examples.py)?  You can use a plugin as follows:

`proxy.py --plugins plugin_examples.RedirectToCustomServerPlugin`
