### ISSUE TITLE
[TLSInterception] Access `HttpParser.host` in https connections

### ISSUE THREAD

**Issue by moham96** [abhinavsingh/proxy.py#722]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a bug report.

**Describe the bug**
Trying to make a plugin that modifies the request if they are made for a specific host, something like this:\

```
def handle_client_request(
        self, request: HttpParser,
) -> Optional[HttpParser]:

    if request.method == httpMethods.POST and request.host in ("httpbin.org","www.httpbin.org"):
        // do something here
        pass
    return request
```
but this doesn't work since request.host is None if TLS interception is enabled, the host only appears in requests of type "CONNECT"

**To Reproduce**
1- Create a plugin that checks the request host or modify the existing "ModifyPostDataPlugin" plugin.
modified version that checks for `httpbin.org` hostname:
```
# -*- coding: utf-8 -*-
"""
    proxy.py
    ~~~~~~~~
    ⚡⚡⚡ Fast, Lightweight, Pluggable, TLS interception capable proxy server focused on
    Network monitoring, controls & Application development, testing, debugging.

    :copyright: (c) 2013-present by Abhinav Singh and contributors.
    :license: BSD, see LICENSE for more details.
"""
from typing import Optional

from ..common.utils import bytes_
from ..http.parser import HttpParser
from ..http.proxy import HttpProxyBasePlugin
from ..http.methods import httpMethods


class ModifyPostDataPlugin(HttpProxyBasePlugin):
    """Modify POST request body before sending to upstream server."""

    MODIFIED_BODY = b'{"key": "modified"}'

    def before_upstream_connection(
            self, request: HttpParser,
    ) -> Optional[HttpParser]:
        return request

    def handle_client_request(
            self, request: HttpParser,
    ) -> Optional[HttpParser]:
        if request.method == httpMethods.POST and request.host in ("httpbin.org","www.httpbin.org"):
            request.body = ModifyPostDataPlugin.MODIFIED_BODY
            # Update Content-Length header only when request is NOT chunked
            # encoded
            if not request.is_chunked_encoded():
                request.add_header(
                    b'Content-Length',
                    bytes_(len(request.body)),
                )
            # Enforce content-type json
            if request.has_header(b'Content-Type'):
                request.del_header(b'Content-Type')
            request.add_header(b'Content-Type', b'application/json')
        return request

    def handle_upstream_chunk(self, chunk: memoryview) -> memoryview:
        return chunk

    def on_upstream_connection_close(self) -> None:
        pass

```
2- Setup and enable [TLS interception](https://github.com/abhinavsingh/proxy.py#tls-interception).
3. Run `proxy.py` as 'proxy --log-level d --plugins proxy.plugin.ModifyPostDataPlugin --ca-key-file ca-key.pem --ca-cert-file ca-cert.pem --ca-signing-key-file ca-signing-key.pem'
4. Run `curl -v -x localhost:8899 -d '{"key": "value"}' --cacert ca-cert.pem  https://httpbin.org/post` and see if the request is modified 
5. You will notice that the request is not modifed because we are checking for the hostname and the host property is `None` on POST and GET requests

**Expected behavior**
I know that TLS connections don't include the server hostname in the packets, it's only included in the "CONNECT" request and not in the subsequent requests, nevertheless for creating plugins it would be nice if the library tracks down the host and set it for checking 

**Version information**
 - OS: Manjaro Linux
 - Browser: Curl
 - Device: Desktop
 - proxy.py running the latest version from git

**Comment by abhinavsingh** [comment]
> request.host in ("httpbin.org","www.httpbin.org"):

You likely want to compare with `bytes` and not `str`.   See type definition for `HttpParser.headers` here:

https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/parser.py#L76-L79

Let me know if it doesn't work

**Comment by moham96** [comment]
> > request.host in ("httpbin.org","www.httpbin.org"):
> 
> You likely want to compare with `bytes` and not `str`. See type definition for `HttpParser.headers` here:
> 
> https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/http/parser.py#L76-L79
> 
> Let me know if it doesn't work

using `HttpParser.headers[b'host'][1]` instead of `HttpParser.host` solved it

**Comment by abhinavsingh** [comment]
> using `HttpParser.headers[b'host'][1]` instead of `HttpParser.host` solved it

You can also better use `parser.header(b'host')` which is a convenient function to return original value from `headers` structure.

I am not sure why the `.host` field isn't being setup correctly for you.  Might have to check it back once with `TLSInterception` enabled.  Thank you for reporting it, will update if I find anything.
