### ISSUE TITLE
Handle signals and shutdown gracefully

### ISSUE THREAD

**Issue by abhinavsingh** [abhinavsingh/proxy.py#745]
**Is your feature request related to a problem? Please describe.**
This happens when you are using `CTRL+C` to terminate `proxy.py` instance.

**Describe the solution you'd like**
`proxy.py` must register for `signals` instead of depending upon `KeyboardInterrupt` and shutdown gracefully.

**Comment by hi-my-name** [comment]
is there a direct link to the site?

**Comment by abhinavsingh** [comment]
> is there a direct link to the site?

which site?

**Comment by hi-my-name** [comment]
to this proxy?

**Comment by abhinavsingh** [comment]
@hi-my-name Sorry its unclear what you are asking.  And most importantly what does it has to do with this issue?

https://github.com/abhinavsingh/proxy.py
http://proxypy.readthedocs.io/

Above are the links.  Enjoy!!!
