### ISSUE TITLE
[Docker] Unable to launch container for `linux/arm64`

### ISSUE THREAD

**Issue by cgchinmay** [abhinavsingh/proxy.py#768]
**Describe the bug**
Built the docker file on `linux/arm64` architecture from the `master` branch
After launching a container, it crashes with following error

```
Traceback (most recent call last):
  File "/usr/local/bin/proxy", line 5, in <module>
    from proxy import entry_point
ModuleNotFoundError: No module named 'proxy'
```

**To Reproduce**
1. docker build -t <image> . 
2. launch container using the above image
4. check pod logs for above error

**Expected behavior**
Container should successfully run

**Comment by abhinavsingh** [comment]
Woopsie!!!  Does the docker container from https://hub.docker.com/repository/docker/abhinavsingh/proxy.py works for you?  Another user reported a similar issue earlier https://github.com/abhinavsingh/proxy.py/issues/566.

I see stable container was release about 10 months ago on `10th Jan`, while master branch was last updated about 9 months ago on `3rd Feb`.  So there are some difference and possibly a broken container (in the master branch) as you found out.

Frankly, we are going to make another release soon.  You can also directly try from `develop` for now.  Lemme dig more and see if I can quick fix the master branch.

**Comment by cgchinmay** [comment]
The container image didn't work for my use case as I am trying to run it on linux/arm64. The image seems to support only [linux/amd64](https://hub.docker.com/r/abhinavsingh/proxy.py/tags). The base image python:3.10-alpine does support arm64 architecture so I tried building the image from the Dockerfile on arm64 machine. The build was successful but got this error while launching the container. If you can check how to support other architectures that would be great. Thanks

**Comment by abhinavsingh** [comment]
> The container image didn't work for my use case as I am trying to run it on linux/arm64. The image seems to support only [linux/amd64](https://hub.docker.com/r/abhinavsingh/proxy.py/tags). The base image python:3.10-alpine does support arm64 architecture so I tried building the image from the Dockerfile on arm64 machine. The build was successful but got this error while launching the container. So if you can provide some guidance in debugging above error that would be great. Thanks

Thank you for bringing this to my notice.  Let me dig into it and update.  Ideally, our `Dockerfile` should build for all arch.  But lemme confirm back on it, possibly send a fix to `develop` or a workaround.

**Comment by abhinavsingh** [comment]
I am wondering is it related to this https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/.  IIUC, some bootstrap steps are required to run docker on `linux/arm64` itself?  Please correct me if wrong.

**Comment by cgchinmay** [comment]
> https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

Yes, we need to build it on arm64 instance to be able to do that but there be could be some other go dependencies in Dockerfile which are not arm compatible yet. Thats what we need to check

**Comment by abhinavsingh** [comment]
> 

`proxy.py` itself has zero-dependency.  We ship `openssl` with container to assist `TLS Interception` and `HTTPS proxy` scenario, otherwise not necessary.

> ModuleNotFoundError: No module named 'proxy'

This to me looks like a `PYTHONPATH` issue?

> Develop vs Master

BTW does `develop` works for you?

**Comment by cgchinmay** [comment]
I tried both, develop and master. got same error. Okay let me check if its Python path issue inside the container. Will get back to you

**Comment by abhinavsingh** [comment]
We are in the middle of setting up automated release.  This PR will also make cross-arch releases.  I am bundling wheel currently, we might have to look into `manylinux` option later for pip wheel.

- https://github.com/abhinavsingh/proxy.py/pull/797

You can try this PR locally like this:

```console
$ make lib-package
$ make container-buildx -e PROXYPY_PKG_PATH=$(ls dist/*.whl)
```

Lemme know how it goes.

**Comment by abhinavsingh** [comment]
@cgchinmay So following PR will fix for `linux/arm64` and provide support for lots of other arch.  However, I haven't yet published the images on docker hub.  But you should be able to create an image locally using the command above.  Read `Makefile` target description for more context and options.

- https://github.com/abhinavsingh/proxy.py/pull/797

I'll close this for now.  Please re-open if issue persists for you on `arm64`.

Once we have completed our release setup, we'll start to also publish container from GHA.  We'll make a dev release (v2.3.2.devXXX.gZZZZZZZ) for every PR merge and a stable release (latest) for every develop to master branch merge.

**Comment by cgchinmay** [comment]
Thank you. I didnt get a chance to try it out. Will reopen the issue if the
problem persists.

**Comment by cgchinmay** [comment]
Thanks, I did face some issues but was able to generate arm compatible image. Posting steps for future reference
```
git checkout v2.4.0rc1

make lib-package

docker buildx build --platform=linux/arm64 -t <repo_name:tag> --build-arg PROXYPY_PKG_PATH=$(ls dist/*.whl) .
```

Other useful info
```
python --version
Python 3.7.10
```

**Comment by abhinavsingh** [comment]
Awesome, thanks for confirmation.

For posterity, same can be also done with;

```console
make container-buildx \
	-e PROXYPY_PKG_PATH=$(ls dist/*.whl) \
	-e BUILDX_TARGET_PLATFORM=linux/arm64 \
	-e PROXYPY_CONTAINER_VERSION=latest
```

I see, we probably must also read tag from environment (within Makefile) to allow override, as you might want to push to something else other than `abhinavsingh/proxy.py` namespace.

**Comment by cgchinmay** [comment]
@abhinavsingh I see that rc images are released. But how do I use them ? don't see them published on dockerhub.

**Comment by abhinavsingh** [comment]
You can try them from here for now https://github.com/abhinavsingh/proxy.py/pkgs/container/proxy.py
