### ISSUE TITLE
Intercept CONNECT request

### ISSUE THREAD

**Issue by DUOLabs333** [abhinavsingh/proxy.py#773]
**Check FAQs**
Please check [Frequently Asked Questions](https://github.com/abhinavsingh/proxy.py#frequently-asked-questions)
before opening a feature request.

**Is your feature request related to a problem? Please describe.**
When trying to log https requests in Firefox, https sites make a CONNECT request to make an encrypted tunnel that even the proxy can't intercept.

**Describe the solution you'd like**
Is there some way of forcing traffic to go through the proxy.

**Describe alternatives you've considered**

**Additional context**
This is probably due to the fact that by setting a proxy in Firefox, it will make CONNECT requests instead of going straight to GET.

**Comment by abhinavsingh** [comment]
Hi @DUOLabs333 , sorry I didn't catch the exact intent.  Did you mean *Websites are bypassing proxy.py* and how to intercept those requests?

**Comment by DUOLabs333** [comment]
No, it's not exactly bypassing on the part of the websites. I was just mistaken (it was not on the fault of proxy.py, but on a website). Just one question -- some sites, like Piped, use Javascript to determine the web page. Is there some way for proxy.py to execute that Javascript in order to get that name? It isn't too important (I'm trying to get the browsing history to save to a file).

**Comment by abhinavsingh** [comment]
> like Piped, use Javascript to determine the web page. Is there some way for proxy.py to execute that Javascript in order to get that name?

I don't know about Piped, but you can always embed custom javascript to be executed on page load, which effectively is equivalent to `proxy.py` executing javascript :D.  But you need to embed it within responses.

**Comment by DUOLabs333** [comment]
How would proxy.py get the resulting content?

**Comment by abhinavsingh** [comment]
> How would proxy.py get the resulting content?

Sorry this looks domain specific.  I am unsure what exactly are you trying to achieve.  I frankly don't use interception much outside of integration with dashboard devtools.   But it's your javascript, you can always send data to wherever you want :)

**Comment by DUOLabs333** [comment]
Ok, thanks for your help.
