### ISSUE TITLE
Browser unable to connect with proxy.py

### ISSUE THREAD

**Issue by puniaze** [abhinavsingh/proxy.py#81]
When I start application in bash terminal, it listens on port that is defined by me. Interestingly, port is okay and listens as expected but neither browser nor I could connect to listened port. It fails to establish connection with browser.

**Comment by abhinavsingh** [comment]
Are you able to access `proxy.py` via `curl`?  Example:

`curl -v -x localhost:8899 http//httpbin.org/get`

**Comment by puniaze** [comment]
Unfortunately, no. Even if I do, nc or telnet to port it returns unable to connect, connection refused. Interestingly, docker image works as expected (probably, it runs on version 0.3) and I can use browser proxy to connect 127.0.0.1:8899.

![image](https://user-images.githubusercontent.com/7716515/65410129-9b628b80-ddfa-11e9-87e3-a9d7e29222ad.png)

![image](https://user-images.githubusercontent.com/7716515/65410147-aa493e00-ddfa-11e9-87a8-732e8b3ecd5f.png)

![image](https://user-images.githubusercontent.com/7716515/65410171-baf9b400-ddfa-11e9-9b04-016bbab1e199.png)

**Comment by puniaze** [comment]
I have found why I failed :)

I just need to run it with these arguments:

python3 proxy.py --port 8080 --hostname 0.0.0.0 --ipv4

**Comment by diepes** [comment]
This seem to be a bug / lack of documentation.

I also got startup 
`2021-12-08 18:26:00,171 - pid:1238993 [I] listen:113 - Listening on ::1:8899`

and no response or logs in terminal

After adding --hostname 0.0.0.0 to proxy command line as suggested by @puniaze  all is fine :)
`2021-12-08 18:27:21,530 - pid:1239156 [I] listen:113 - Listening on 0.0.0.0:8899`

**Comment by abhinavsingh** [comment]
I guess we must use `IPv4` by default.  We use `IPv6` binding and it doesn't seem to fit well for everyone.  Example, on my Mac I don't need to do anything, because my `/etc/hosts` file contain this entry by default:

```console
cat /etc/hosts                                                                                                                                                                                                          ─╯
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

What OS are you using?

You can try adding `::1             localhost` entry to your `/etc/hostname` or `/etc/hosts` depending upon ur OS.  If on Windows, please dig the internet on how to add one.
