### ISSUE TITLE
SSL Interception Support

### ISSUE THREAD

**Issue by puniaze** [abhinavsingh/proxy.py#84]
This project would be awesome if it supported SSL Proxy like in [this project](https://github.com/inaz2/proxy2).

The project I mentioned has memory consumption problems so that is why it is not reasonable to use it.

Please keep your project up-to-date, as it seems this will become one of the best programmable proxy server!

**Comment by abhinavsingh** [comment]
@puniaze Are you referring to _dynamic certificate generation for HTTPS intercept_ support? Thanks for the kind words :)

**Comment by puniaze** [comment]
Yes, I meant intercepting ssl traffic using self-signed certificate. It is like doing mitm but for revealing contents of payload.

**Comment by abhinavsingh** [comment]
@puniaze Give it a shot, try from https://github.com/abhinavsingh/proxy.py/tree/interceptor branch.  See https://github.com/abhinavsingh/proxy.py/blob/interceptor/README.md for some details on how to enable interception. Let me know how it goes :)

**Comment by puniaze** [comment]
Great! It would be great pleasure to test it!
