### ISSUE TITLE
Disable SSLv3 handshakes

### ISSUE THREAD

**Issue by puniaze** [abhinavsingh/proxy.py#87]
Intercept works as expected but has small issues.

I run proxy.py with these arguments:

`python3 proxy.py --hostname 0.0.0.0 --port 8080 --ca-cert-dir=.  --ca-key-file=ca-key.pem --ca-cert-file=ca-cert.pem --ca-signing-key=ca-signing-key.pem --plugins plugin_examples.FilterByTargetDomainPlugin`

And get multiple errors like shown in this picture:

![image](https://user-images.githubusercontent.com/7716515/65492327-c19f2e80-dec1-11e9-90b5-373fb8b5648f.png)

During SSL connections it was not possible to get full URL of requested resource:

![image](https://user-images.githubusercontent.com/7716515/65492500-1b075d80-dec2-11e9-88dc-b8e31ca41bcc.png)

Additionally, could you please give us plugin examples that could manipulate response data?

**Comment by abhinavsingh** [comment]
Looks like upstream server `upload.az` is trying to negotiate `SSLv3`.  I have disable negotiation using older SSL version.  This commit should address the error you faced here https://github.com/abhinavsingh/proxy.py/commit/99c1fa795e560df546933f3b5d9f812ec5527e2e

Please give it a try and let me know. Thank you :)
