### ISSUE TITLE
Caching disabled due to excetion message 'int' object has no attribute 'hex' 

### ISSUE THREAD

**Issue by Htech155** [abhinavsingh/proxy.py#872]
**Describe the bug**
When running the plugin.CacheResponsesPlugin errors are given for attempted request caches. 

**To Reproduce**
1. Run `proxy.py --plugins proxy.plugin.CacheResponsesPlugin --cache-dir /tmp/ `
2. Make HTTP requests to the proxy and watch the cache errors flow in.

**Expected behavior**
The expected behavior is for the proxy to cache the request for retrieval on next request. 

**Version information**
 - OS: Ubuntu 20.04
 - Device: Lenovo Thinkpad X1
 - proxy.py Version 2.4.0rc2

**Additional context**
I was able to pin point the area where the error originates to [Code link](https://github.com/abhinavsingh/proxy.py/blob/0d12873e9e4cbcc5b73e93d096d4ae3764d208a0/proxy/plugin/cache/store/disk.py#L46) 

I was able to rewrite this line to solve the error, the problem seems to be that .hex is being called on a int object. The solution that worked for me was to change the .hex to a str()

Here is my version of the file [Working caching proxy](https://imgur.com/a/gJ5wgIF) 

**Screenshots**
[Error Screenshot](https://imgur.com/a/vCBdSt9)

**Comment by abhinavsingh** [comment]
Thank you for reporting the bug.  This will be fixed in https://github.com/abhinavsingh/proxy.py/pull/866.  Haven't really merged it yet because of unrelated CI issue.

Try out the branch from this PR and everything should work fine.  Let me know

**Comment by abhinavsingh** [comment]
Please try now from develop branch, PR has been merged.  Reopen if problem persists.
