### ISSUE TITLE
Is there a way to get the access log programatically?

### ISSUE THREAD

**Issue by AsafMah** [abhinavsingh/proxy.py#909]
Hey, I want to test my code when going through a proxy.
Proxy.py is a great solution, but I want in the end of the test to see the list of requests that actually went through the proxy.
I know I can setup a log file and then parse it, but that's not ideal.

Is there a way to get all of the requests that went through the proxy as a python list/object? 

Thanks

**Comment by abhinavsingh** [comment]
Yes, you can get access to the logs programmatically.  You need to write a plugin for it.  Example, `ProxyPoolPlugin` utilizes `on_access_log` hook, see https://github.com/abhinavsingh/proxy.py/blob/develop/proxy/plugin/proxy_pool.py#L198-L212

Also look at formal definition of `on_access_log` here https://github.com/abhinavsingh/proxy.py/blob/d4449b8644e75897719305f34193b34e258357e4/proxy/http/proxy/plugin.py#L166-L178

Once you have a plugin with custom `on_access_log` handler, you can choose to do whatever you want within you Python code.  Write to a database, on disk, in-memory data structure, anything.

Let me know how it goes for you.
