### ISSUE TITLE
Related to HTTPS proxy request and SSL handshake

### ISSUE THREAD

**Issue by MayankFawkes** [abhinavsingh/proxy.py#95]
Hello

I am actually trying to capture requests I created a socket on port 12345 and with curl, I am sending a request to my own server with command "curl -x http://127.0.0.1:12345 http://google.com" and I am getting correct get request but when I change HTTP to HTTPS in google then it sends connect request to my server and I don't know how to handle it.
when I used HTTP 
b'GET http://google.com/ HTTP/1.1\r\nHost: google.com\r\nUser-Agent: curl/7.55.1\r\nAccept: */*\r\nProxy-Connection: Keep-Alive\r\n\r\n'

and when I used https
b'CONNECT google.com:443 HTTP/1.1\r\nHost: google.com:443\r\nUser-Agent: curl/7.55.1\r\nProxy-Connection: Keep-Alive\r\n\r\n'

I read on some forum and according to them for SSL browser send connect request first to check if that website reachable or not then the proxy server will reply with HTTP/1.1 200 Connection Established\r\n this means proxy server says connection to that website is successful then next step is SSL/ handshake and I don't know what do now I am stuck at this point.

any help from your side much appreciated.

Thanks

**Comment by abhinavsingh** [comment]
Hi @MayankFawkes , I'll recommend you to visit [stackoverflow](https://stackoverflow.com) for asking such questions.  Github issues are meant for questions pertaining to `proxy.py` only.  Fwiw, you can also read `proxy.py` code and understand whats going under the hood.  Check  https://github.com/abhinavsingh/proxy.py#plugin-developer-and-contributor-guide for high level internals intro.
